const assert=require('assert');const L=require('../carrera-rounds.js');
let s=L.fresh(3);
[0,1,2].forEach(i=>L.toggle(s,0,i));assert.strictEqual(L.crowns(s.cells),1,'3 casilleros = 1 corona');
L.toggle(s,0,2);assert.strictEqual(L.crowns(s.cells),0,'destachar quita la corona');
L.toggle(s,0,2);
[1,2].forEach(r=>[0,1,2].forEach(i=>L.toggle(s,r,i)));
assert.strictEqual(s.over.kind,'win');assert.strictEqual(s.over.reason,'coronas','3 coronas gana');
L.undo(s);assert.strictEqual(s.over,null,'deshacer reabre');assert.strictEqual(L.crowns(s.cells),2);
let t=L.fresh(3,5);t.endAt=1000;L.settle(t,1001);assert.deepStrictEqual(t.over,{kind:'draw',reason:'tiempo'},'empate por tiempo 0-0');
t=L.fresh(3,5);t.endAt=1000;[0,1,2].forEach(i=>L.toggle(t,0,i,10));L.settle(t,1001);assert.deepStrictEqual(t.over,{kind:'win',reason:'tiempo'},'más coronas al terminar el tiempo gana');
L.undo(t);L.undo(t);L.undo(t);assert.strictEqual(L.crowns(t.cells),0);
let u=L.fresh(3);[1,1,1].forEach(d=>L.setRival(u,d));assert.deepStrictEqual(u.over,{kind:'lose',reason:'coronas'},'rival llega a 3');
L.undo(u);assert.strictEqual(u.rival,2);assert.strictEqual(u.over,null);
let r=L.fresh(3,10);[0,1,2].forEach(i=>L.toggle(r,2,i));L.setRival(r,2);const r2=L.restart(r);
assert.strictEqual(L.crowns(r2.cells),0);assert.strictEqual(r2.rival,0);assert.strictEqual(r2.target,3);assert.strictEqual(r2.mins,10);assert.strictEqual(r2.over,null,'reiniciar limpia hoja y conserva config');
let v=L.fresh(3);L.setRival(v,1);L.applyRival(v,2);
assert.strictEqual(v.rival,2,'applyRival fija el rival');assert.ok(!v.hist.some(h=>h.t==='r'),'applyRival limpia el historial manual del rival');
L.applyRival(v,3);assert.deepStrictEqual(v.over,{kind:'lose',reason:'coronas'},'rival en vivo llega a 3');
L.applyRival(v,2);assert.strictEqual(v.over,null,'si el rival baja, se reabre');
console.log('carrera: OK');
