/* Original hub and buzzer DOM; only identity and transport are replaced. */
(function(){let game=null,player=null,pending=false,lastTurn='',lastQuestion='';const $=V.$;
selectGame=function(id){game=id==='quien'?'qld':id;if(game==='impostor'){location.href='velada.html#impostor';return}player=null;show('team-select-screen');paint()};
selectTeam=function(id){player=V.person(id);if(!player)return;localStorage.setItem('velada-v3:player',id);const g=match();if(!g)return;if(['erudito','palabras'].includes(game)){location.href=V.files[game]+'?mode=participant&partida='+g.id+'&player='+id;return}show('buzz-screen');paint()};
goBack=function(to){player=null;hideResult();hideBzCountdown();if(to==='game'){game=null;show('game-select-screen')}else{show('team-select-screen');paint()}};
const originalCheckPw=checkPw;checkPw=function(){if(VeladaAccess.valid($('pw-input').value))VeladaAccess.remember();return originalCheckPw();};
function match(){const all=Object.values(V.s?.sessions||{}).filter(g=>g.game===game&&!['done','closed'].includes(g.status));return all.find(g=>!player||g.teamIds.includes(player.teamId))||null}
function paint(){if(!game)return;const g=match();$('ts-icon').textContent=V.icons[game]||'🎮';$('ts-name').textContent=V.M.GAMES[game]?.name||game;$('ts-section-label').textContent=g?'¿Quién sos?':'Esperando que el conductor active el juego';$('team-list-standard').style.display='none';$('edit-names-btn').style.display='none';$('connecting-dot').style.display='none';$('connecting-text').textContent=V.status();const list=$('team-list-individual');list.style.display='grid';list.innerHTML=(V.s?.participants||[]).filter(p=>g?.teamIds.includes(p.teamId)).map(p=>`<button class="team-btn team-indiv v-player" data-v="choose-person:${p.id}">${V.photo(p)}<span class="indiv-name">${V.esc(p.name)}</span><small>${V.esc(V.name(p.teamId))}</small></button>`).join('');
 if(!player)return;if(!g||!V.person(player.id)){player=null;show('team-select-screen');return}V.sessionId=g.id;player=V.person(player.id);const side=V.M.sideFor(V.s,g,player.teamId),online=V.store.online&&V.store.ready&&V.store.status==='online',turn=online&&g.active===side,queued=g.queue.includes(side),used=g.failed.includes(side);const enabled=online&&!V.s.panic?.on&&!pending&&!queued&&!used&&!g.steal&&['open','answering'].includes(g.status);
 const button=$('bz-buzz-btn');button.disabled=!enabled;button.className='bz-buzz-btn '+(enabled?'open':'locked')+(turn?' won-me':'')+' team-'+(g.game==='argentinos'?side:V.s.teams.findIndex(t=>t.id===player.teamId)%2?'b':'a');$('bz-game-tag').textContent=V.M.GAMES[game].name;$('bz-team-name').textContent=player.name+' · '+V.name(player.teamId);$('bz-status').textContent=!online?'Sin conexión · buzzer bloqueado':V.s.panic?.on?'⏸ Noche pausada por el conductor':turn?'🏆 Turno confirmado de tu equipo':used?'Tu equipo ya usó su oportunidad':queued?'Pulsación confirmada · posición '+(g.queue.indexOf(side)+1):pending?'Enviando · esperando confirmación':enabled?'¡Tocá cuando sepas la respuesta!':'Esperando al conductor…';$('bz-status').className='bz-status '+(turn?'won':enabled?'open':'');
 let info=$('v-buzzer-info');if(!info){info=document.createElement('div');info.id='v-buzzer-info';info.className='v-queue';$('bz-reacts').before(info)}const sideName=x=>g.game==='argentinos'?g.groups[x]?.name:V.name(x);info.innerHTML=`${g.timer?`<b data-v-timer="${g.id}" style="font-size:28px"></b> segundos<br>`:''}${online&&g.active?'Responde: '+V.esc(sideName(g.active))+'<br>':''}${online&&g.queue.length?'Orden confirmado: '+g.queue.map(sideName).map(V.esc).join(' → '):''}`;
 const key=g.questionId+':'+g.active;if(lastQuestion!==g.questionId){lastQuestion=g.questionId;lastTurn='';hideResult()}if(turn&&key!==lastTurn){lastTurn=key;showResult(true,player.name);$('bz-result-title').textContent='¡Es tu turno!';$('bz-result-sub').textContent='Confirmado para '+V.name(player.teamId);sfxTin();navigator.vibrate?.([60,40,60]);setTimeout(hideResult,1600)}if(!turn)hideResult();}
 doBuzz=async function(){const g=match();if(!g||!player||pending||$('bz-buzz-btn').disabled)return;pending=true;paint();try{await V.act({type:'buzz',sessionId:g.id,questionId:g.questionId,teamId:player.teamId,playerId:player.id})}catch(e){V.toast(e.message)}finally{pending=false;paint()}};
 V.handlers['choose-person']=id=>selectTeam(id);sendReact=emoji=>{if(V.store.db&&V.store.online)V.store.db.ref(V.store.root+'/reactions').push({emoji,at:firebase.database.ServerValue.TIMESTAMP}).catch(e=>V.toast(e.message))};
 const old=$('bz-buzz-btn'),fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.removeAttribute('onclick');fresh.addEventListener('pointerdown',e=>{if(e.button!==0||fresh.disabled)return;e.preventDefault();doBuzz()});fresh.addEventListener('click',e=>{if(e.detail===0)doBuzz()});
 const direct=V.q.get('game');V.on(paint);V.ready.then(()=>{if(direct){dismissSplash();selectGame(direct)}});
 const imp=document.querySelector('.game-impostor');if(imp)imp.onclick=()=>location.href='velada.html#impostor';
})();

function updateGameMenu(){const root=document.querySelector('#game-select-screen .sm-mini');if(!root)return;const list=Object.entries(V.M.GAMES).filter(([k])=>!['movies','qld','argentinos','erudito','palabras','impostor'].includes(k));const signature=JSON.stringify(list);if(root.dataset.extraGames===signature)return;root.dataset.extraGames=signature;root.querySelectorAll('[data-extra-game]').forEach(e=>e.remove());for(const [k,g]of list){const b=document.createElement('button');b.dataset.extraGame=k;b.className='game-btn';b.innerHTML='<span class="game-btn-icon">'+(V.icons[k]||'🎮')+'</span><div class="game-btn-info"><span class="game-btn-name">'+V.esc(g.name)+'</span><span class="game-btn-sub">Marcador del conductor</span></div>';b.onclick=()=>selectGame(k);root.append(b)}}V.on(updateGameMenu);V.ready.then(updateGameMenu);
