/* Validated JSON exchange shared by the original editors. */
(function(){const E=V.esc,B=V.btn;function validate(game,input){const arr=Array.isArray(input)?input:input?.cards||input?.deck;if(!Array.isArray(arr))throw Error('El JSON debe contener una lista de cartas');if(arr.length>5000)throw Error('Máximo 5000 cartas por mazo');const seen=new Set();return arr.map((raw,i)=>{let c=typeof raw==='string'?{name:raw,word:raw}:raw;if(!c||typeof c!=='object'||Array.isArray(c))throw Error('Carta '+(i+1)+': formato inválido');c={...c};const str=k=>typeof c[k]==='string'&&c[k].trim();if(game==='movies'&&(!['movie','song'].includes(c.type)||!str('title')))throw Error('Carta '+(i+1)+': falta título o tipo movie/song');if(game==='qld'&&!str('prompt')&&!str('title'))throw Error('Carta '+(i+1)+': falta frase o título');if(game==='argentinos'){if(!str('q')||!Array.isArray(c.a)||!c.a.length||c.a.length>12)throw Error('Pregunta '+(i+1)+': falta pregunta o entre 1 y 12 respuestas');c.a=c.a.map(a=>Array.isArray(a)?{t:a[0],v:a[1]}:a);if(c.a.some(a=>typeof a.t!=='string'||!a.t.trim()||!Number.isInteger(a.v)||a.v<0||a.v>100))throw Error('Pregunta '+(i+1)+': respuestas con texto y votos enteros de 0 a 100');}if(game==='palabras'&&!str('name'))throw Error('Categoría '+(i+1)+': falta nombre');if(game==='impostor'&&!str('word'))throw Error('Palabra '+(i+1)+': falta word');if(c.id==null||seen.has(String(c.id)))c.id=V.M.id();seen.add(String(c.id));return c})}window.VeladaValidateDeck=validate;
function current(game){if(game===V.kind&&['movies','qld','palabras'].includes(game))return deck;if(game===V.kind&&game==='argentinos')return bank;if(game==='impostor'&&window.impDeckExport)return impDeckExport();return V.store.deckCache[game]||[]}
async function apply(game,cards){cards=validate(game,cards);await V.store.saveDeck(game,cards);if(game===V.kind){if(game==='movies'){deck=cards;order=deck.map((_,i)=>i);cardIdx=0;nextId=Math.max(200,...deck.map(c=>Number(c.id)||0))+1;renderDeckList();renderCondCard();updateCount();sendState()}if(game==='qld'){deck=cards;cardIdx=0;saveIdx();renderCard();renderEditorList()}if(game==='argentinos'){bank=cards.map(normBankItem);renderDeckList();syncUI()}if(game==='palabras'){deck=cards;renderDeckList();syncUI()}}if(game==='impostor'&&window.impDeckApply)impDeckApply(cards);V.toast('Mazo guardado: '+cards.length+' cartas')}
V.handlers['deck-export']=async(game=V.kind)=>{await V.store.deck(game);V.download(game+'-mazo.json',current(game))};V.handlers['deck-empty']=async(game=V.kind)=>{if(confirm('¿Vaciar el mazo de '+V.M.GAMES[game].name+'? Podés exportarlo antes.'))await apply(game,[])};
V.handlers['deck-import']=(game=V.kind)=>{const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>V.run(async()=>{const file=input.files[0];if(!file)return;if(file.size>24*1024*1024)throw Error('Máximo 24 MB por archivo');const cards=validate(game,JSON.parse(await file.text()));await V.store.deck(game);V.dialog('Importar · '+V.M.GAMES[game].name,`<form><p>${cards.length} cartas válidas. El mazo actual tiene ${current(game).length}.</p><div class="v-note">${cards.slice(0,5).map(c=>E(c.title||c.q||c.name||c.word||c.prompt)).join('<br>')||'Mazo vacío'}</div>${V.select('mode','Cómo importar',[['add','Agregar al mazo'],['replace','Reemplazar el mazo']])}<button class="primary">Confirmar importación</button></form>`,fd=>apply(game,fd.get('mode')==='replace'?cards:current(game).concat(cards.map(c=>({...c,id:V.M.id()}))))) });input.click()};
V.handlers.decks=()=>V.dialog('Mazos de la velada',`<div class="v-stack">${['movies','argentinos','qld','impostor','palabras'].map(k=>`<div class="v-note"><h3>${E(V.M.GAMES[k].name)}</h3>${B('Exportar JSON','deck-export:'+k)}${B('Importar JSON','deck-import:'+k)}${B('Vaciar','deck-empty:'+k)}</div>`).join('')}</div>`);
if(V.kind==='movies')importDeckJson=()=>V.handlers['deck-import']();if(V.kind==='qld')importDeck=()=>V.handlers['deck-import']();if(V.kind==='argentinos'){
 importBankFile=()=>V.handlers['deck-import']();normBankItem=item=>({...item,id:item.id??V.M.id(),q:String(item.q),a:(item.a||[]).map(x=>Array.isArray(x)?{t:String(x[0]),v:Number(x[1])}:{t:String(x.t),v:Number(x.v)}).sort((a,b)=>b.v-a.v),enabled:item.enabled!==false});
 const oldRender=renderDeckList;renderDeckList=function(){oldRender();document.querySelectorAll('#deck-list .deck-row').forEach((r,i)=>r.insertAdjacentHTML('beforeend',B('Editar','survey-edit:'+i)))};
 V.handlers['survey-edit']=i=>{i=Number(i);const c=bank[i]||{q:'',a:[],image:''};let answers=c.a.length?c.a.map(a=>({...a})):[{t:'',v:0}];
 const d=V.dialog(bank[i]?'Editar pregunta':'Nueva pregunta',`<form><div class="card">${V.field('q','Pregunta',c.q)}<label>Imagen de referencia<input name="image" type="file" accept="image/*"></label>${c.image?`<img src="${E(c.image)}" alt="Referencia" style="max-width:100%;max-height:180px">`:''}</div><div class="v-answer-list"></div><button type="button" class="v-btn" id="v-answer-add">+ Agregar respuesta</button><p class="v-muted">La más votada será la respuesta n.º 1. Hasta 12 respuestas, con votos de 0 a 100.</p><button class="primary">Guardar pregunta</button></form>`,async fd=>{read();const file=fd.get('image'),item={...c,q:fd.get('q'),a:answers,image:file?.size?await V.image(file):c.image||''};const list=bank.slice();if(bank[i])list[i]=item;else list.push(item);await apply('argentinos',list)});
 function read(){answers=[...d.querySelectorAll('.v-answer-row')].map(r=>({t:r.querySelector('[name=answer_text]').value.trim(),v:Number(r.querySelector('[name=answer_votes]').value)}))}
 function paint(){d.querySelector('.v-answer-list').innerHTML=answers.map((a,n)=>`<div class="v-answer-row"><label>Respuesta ${n+1}<input name="answer_text" value="${E(a.t)}" required></label><label>Votos<input name="answer_votes" value="${E(a.v)}" type="number" min="0" max="100" step="1" required></label><button type="button" class="v-btn" data-remove-answer="${n}" aria-label="Quitar respuesta">×</button></div>`).join('');d.querySelector('#v-answer-add').disabled=answers.length>=12;d.querySelectorAll('[data-remove-answer]').forEach(b=>b.onclick=()=>{read();answers.splice(Number(b.dataset.removeAnswer),1);paint()})}
 d.querySelector('#v-answer-add').onclick=()=>{read();answers.push({t:'',v:0});paint();d.querySelector('.v-answer-row:last-child input').focus()};paint();
 };addBankQuestion=()=>V.handlers['survey-edit'](bank.length);
}

function decorate(){if(!V.host)return;for(const id of ['deck-panel','deck-overlay','editor-overlay']){const el=V.$(id);if(!el||el.querySelector('.v-deck-tools'))continue;const box=document.createElement('div');box.className='v-row v-deck-tools';box.style.padding='12px';box.innerHTML=B('Exportar JSON','deck-export')+B('Importar JSON','deck-import')+B('Vaciar mazo','deck-empty');(el.querySelector('.sheet,.editor-panel,.deck-panel')||el).append(box)}}V.ready.then(decorate);document.addEventListener('keydown',e=>{if(e.key==='Escape')for(const id of ['deck-ov','deck-overlay','editor-overlay'])V.$(id)?.classList.remove('open')});
})();
