/* Adapter over the original full game interfaces, media players and editors. */
(function(){const k=V.kind,$=V.$;let ready=false,restoring=false,loaded='',lastCard=null,publishTimer,privateSig='',publicSig='',busy=Promise.resolve(),liveStop=null;
const serial=fn=>{busy=busy.catch(()=>{}).then(fn);busy.catch(e=>V.toast(e.message));return busy};
function game(){const g=V.g;if(!g)throw Error('Activá primero este juego desde el panel');V.sessionId=g.id;return g}
function scores(){const g=V.g;if(!g)return;let e=$('v-native-scores');if(!e){e=document.createElement('div');e.id='v-native-scores';e.className='v-scoreboard';$('v-toolbar').after(e)}if(k==='argentinos'){e.innerHTML=V.host&&g.active&&!g.steal?V.btn('Pasar control al otro lado','survey-pass'):'';return;}e.innerHTML=g.teamIds.map(t=>`<div class="v-score">${V.esc(V.name(t))}<small>${V.s.participants.filter(p=>p.teamId===t).map(p=>V.esc(p.name)).join(' · ')}</small><b>${g.scores[t]||0}</b>${V.host?V.btn('−','native-score:'+t+':-1')+V.btn('+','native-score:'+t+':1'):''}</div>`).join('')}
V.handlers['native-score']=async(t,d)=>{const g=game();await V.act({type:'score',sessionId:g.id,teamId:t,value:Math.max(0,(g.scores[t]||0)+Number(d))});schedule()};
function schedule(){if(!V.host||!ready||restoring)return;clearTimeout(publishTimer);publishTimer=setTimeout(()=>serial(persist),90)}
async function persist(){if(!ready||restoring||!V.g)return;const g=game(),n=native(),safe=view(),ns=JSON.stringify(n),ps=JSON.stringify(safe);if(ns!==privateSig){await V.store.native(g.id,n);privateSig=ns}if(ps!==publicSig){await V.store.publish(g.id,safe);publicSig=ps}}
async function ensureCard(){const g=game(),c=k==='movies'||k==='qld'?currentCard():null;if(c&&String(c.id)!==lastCard){await V.act({type:'next',sessionId:g.id,index:cardIdx,card:{q:k==='qld'?c.prompt||'':''},questionId:V.M.id()});lastCard=String(c.id)}return V.g}
async function open(){await ensureCard();const g=game();if(!['open','answering'].includes(g.status))await V.act({type:'open',sessionId:g.id,questionId:V.M.id()});sync();schedule()}
function native(){if(k==='movies')return{order,cardIdx,revealed,phase,frameIdx,revealProgress,gridRevealed,lyricLine,emojiStep,bonusShown,bonusRevealed,bonusAwardTeam};if(k==='qld')return{cardIdx,revealed,hintsShown,videoSyncState,revealCueState};if(k==='argentinos')return{round,used:Array.from(usedQ),fm,targetScore};return{selectedCat,usedCats:Array.from(usedCats),score,roundsLog,roundBaseline}}
let guessView=null;
function view(){if(k==='movies'){const x=guessView?V.M.copy(guessView):{};if(x.phase!=='reveal')delete x.cardTitle;return{...x,teams:V.g.teamIds.map(t=>({id:t,name:V.name(t),score:V.g.scores[t]||0})),timer:V.g.timer||null}}if(k==='qld'){const s=liveStateSnapshot(),cur=currentCard();if(s.card&&cur){if(String(cur.mediaData||'').startsWith('data:image/')){s.card.mediaUrl=cur.mediaData;s.card.mediaIsLocal=false}s.card.options=normOptions(cur).map(o=>({text:o.text,img:o.img||''}))}if(!s.revealed&&s.card){s.card.who='';s.card.ending='';s.card.title=''}return{...s,t:0,teams, timer:V.g.timer||null}}if(k==='argentinos'){const s=snapshot();s.t=0;if(s.round)s.round.ans=s.round.ans.map(a=>a.rev||s.round.phase==='over'?a:{rev:false,owner:null,t:'',v:0});return{...s,timer:V.g.timer||null}}return{selectedCat,score,teamNames}}
function applyPublic(data){if(!data)return;if(k==='movies'){renderParticipant(data);guessView=data}else if(k==='qld'){if(data.teams)applyTeams(data.teams);applyLive(data)}else if(k==='argentinos'){renderParticipant(data,pLastSnap);pLastSnap=data}else{selectedCat=data.selectedCat;score=data.score;teamNames=data.teamNames;syncUI();syncScoreUI()}scores()}
async function boot(){const g=V.g;if(!g){V.toolbar();return}V.sessionId=g.id;if(loaded===g.id)return;if(V.host&&V.store.db&&!V.store.authorized){V.toolbar();return}loaded=g.id;restoring=true;ready=false;try{
 if(!V.host){if(k!=='palabras')applyMode('participant');else{document.querySelectorAll('button').forEach(b=>b.disabled=true);document.querySelectorAll('.footer-links,.sb-controls,.var-section').forEach(e=>e.style.display='none')}document.body.classList.add('v-native-readonly');if(k==='movies')document.querySelector('#participant .part-sb')?.classList.add('v-hidden');liveStop?.();liveStop=V.store.watchLive(g.id,applyPublic);ready=true;return}
 const cards=await V.store.deck(k),saved=await V.store.readNative(g.id);
 if(k==='movies'){MODE='conductor';$('mode-gate').classList.remove('open');$('conductor').classList.add('active');deck=cards;nextId=Math.max(200,...deck.map(c=>Number(c.id)||0))+1;order=saved?.order||deck.map((_,i)=>i);order=order.filter(i=>i>=0&&i<deck.length);cardIdx=saved?.cardIdx||0;revealed=!!saved?.revealed;phase=saved?.phase||'idle';frameIdx=saved?.frameIdx||0;revealProgress=saved?.revealProgress||0;gridRevealed=saved?.gridRevealed||[];lyricLine=saved?.lyricLine||0;emojiStep=saved?.emojiStep||1;bonusShown=!!saved?.bonusShown;bonusRevealed=!!saved?.bonusRevealed;bonusAwardTeam=saved?.bonusAwardTeam||null;nameA=V.name(g.teamIds[0]);nameB=V.name(g.teamIds[1]);timerDefault=V.s.settings.games.movies.seconds;syncNamesUI();renderCondCard();updateCount();syncPhaseUI();syncRevealUI();syncMuteBtns();initShortcutsDock();document.querySelector('#conductor .score-bar')?.classList.add('v-hidden');document.querySelector('#participant .part-sb')?.classList.add('v-hidden');$('tbtn-stop').onclick=()=>V.action({type:'timer',sessionId:game().id,command:'pause'});$('act-idle').innerHTML=V.btn('🔔 Abrir buzzer','native-open')+V.btn('↻ Repetir orden del buzzer','native-retry')+V.btn('→ Pasar carta','native-pass');lastCard=saved&&currentCard()?String(currentCard().id):null;
 }else if(k==='qld'){MODE='conductor';$('gate').style.display='none';$('conductor').classList.add('active');deck=cards;cardIdx=saved?.cardIdx||0;revealed=!!saved?.revealed;hintsShown=saved?.hintsShown||{1:false,2:false};applyTeams(g.teamIds.map((id,index)=>({index,label:V.name(id),members:V.s.participants.filter(p=>p.teamId===id).map(p=>p.name),membersFull:[]})));renderCard();populateCategoryOptions();renderRoundStatus();lastCard=saved&&currentCard()?String(currentCard().id):null;document.querySelector('#conductor .scoreboard')?.classList.add('v-hidden');let extra=document.createElement('div');extra.className='v-row';extra.innerHTML=V.btn('✗ Incorrecto · cerrar oportunidad','native-wrong')+'<b data-v-timer="'+g.id+'"></b>';document.querySelector('#conductor').prepend(extra);
 }else if(k==='argentinos'){MODE='conductor';$('mode-gate').classList.remove('open');document.body.classList.add('is-conductor');bank=cards.map(c=>normBankItem(c));teamNames={a:g.groups.a.name,b:g.groups.b.name};targetScore=saved?.targetScore||0;usedQ=new Set(saved?.used||[]);round=saved?.round||null;fm=saved?.fm||null;roundTimerSecs=40;syncUI();syncScoreUI();renderMetaBtn();if(round){$('round-cover').classList.add('open');$('round-question').textContent=round.q;renderPanel();renderPot();renderStrikes();setPhase(round.phase)}initShortcutsDock();syncMuteBtn();
 }else{deck=cards.map(c=>({...c,enabled:c.enabled!==false}));selectedCat=saved?.selectedCat||null;usedCats=new Set(saved?.usedCats||[]);score=saved?.score||{a:0,b:0};teamNames={a:V.name(g.teamIds[0]),b:V.name(g.teamIds[1])};roundsLog=saved?.roundsLog||[];roundBaseline=saved?.roundBaseline||null;syncUI();syncScoreUI();document.querySelectorAll('[onclick*="Comodin"],[onclick*="rerollShared"]').forEach(e=>e.style.display='none')}
 ready=true;
 }catch(e){loaded='';V.toast(e.message)}finally{restoring=false;V.toolbar();sync();if(V.host&&ready){if(k==='movies')sendState();schedule()}}}
function sync(){V.toolbar();if(!ready||!V.g)return;scores();const g=V.g;if(!V.host)return;if(k==='movies'){const current=g.active;nameA=current?V.name(current):V.name(g.teamIds[0]);nameB=V.name(g.teamIds[1]);activeBuzzer=current?'a':null;phase=g.status==='answering'?'playing_a':g.status==='revealed'?'reveal':'idle';syncNamesUI();syncPhaseUI();timerActive=!!g.timer?.running;timerLeft=g.timer?Math.ceil(Math.max(0,g.timer.running?g.timer.endAt-V.store.now():g.timer.remaining)/1000):timerDefault;syncTimerUI();$('tbtn-start').style.display=timerActive?'none':'';$('tbtn-stop').style.display=timerActive?'':'none';setFbStatus(V.store.online?'ready':'error',V.status());sendState();
 }else if(k==='qld'){window.qldPhotos=Object.fromEntries(V.s.participants.filter(p=>p.photo).map(p=>[p.name,p.photo]));teamScores=Object.fromEntries(g.teamIds.map((t,i)=>[i,g.scores[t]||0]));_winnerTeamIdx=g.active?g.teamIds.indexOf(g.active):null;_winnerName=g.active?V.name(g.active):null;buzzerState=g.active?'won':['open','answering'].includes(g.status)?'open':'locked';buzzerWinner=g.active?{name:V.name(g.active)}:null;renderBuzzerBanner();renderScores();if(g.status==='revealed'&&!revealed){revealed=true;renderCard();schedule()}const e=$('fb-txt')||$('fb-status');if(e)e.textContent=g.active?'Responde: '+V.name(g.active):V.status();
 }else if(k==='argentinos'){score=g.sideScores||{a:0,b:0};_bzOpen=['open','answering'].includes(g.status);_bzState=g.active?'won':_bzOpen?'open':'locked';renderBzToggle();syncScoreUI();if(round){round.revealed=round.a.map((_,i)=>g.revealed.includes(i));round.owner=round.a.map((_,i)=>g.revealed.includes(i)?g.control:null);round.pot=g.pot||0;round.strikes=g.strikes||0;round.buzzWinner=g.queue[0]||null;round.responder=g.active;round.controlTeam=g.steal?g.originalControl:g.control;round.winner=g.potAwarded||null;const p=g.status==='revealed'?'over':g.steal?'steal':g.status==='answering'?'play':'faceoff';setPhase(p);renderPanel();renderPot();$('undo-btn').disabled=!(V.s.sessionHistory[g.id]?.length);$('undo-strike-btn').disabled=!(V.s.sessionHistory[g.id]?.length);if(g.status==='revealed'){const e=$('round-end');e.innerHTML='<h2>Ronda terminada</h2><p>Pozo para '+V.esc(g.groups[g.potAwarded]?.name||'—')+'</p><button class="btn-primary" onclick="closeRound()">Siguiente ronda →</button>'}schedule()}}
}
V.handlers['survey-pass']=()=>V.act({type:'surveyPass',sessionId:game().id});
V.handlers['native-open']=()=>serial(open);V.handlers['native-pass']=()=>passCard();V.handlers['native-retry']=()=>serial(()=>V.act({type:'restartQueue',sessionId:game().id}));V.handlers['native-wrong']=()=>serial(async()=>{await V.act({type:'verdict',sessionId:game().id,ok:false});sync();schedule()});
if(k==='movies'){
 broadcast=()=>{};fbPushState=st=>{guessView=st;schedule()};fbOpenBuzzer=()=>serial(open);fbLock=()=>{};gmsSendVerdict=()=>{};saveScore=()=>{};saveOrder=()=>schedule();saveDeck=()=>V.run(()=>V.store.saveDeck(k,deck));saveDeckToFirebase=()=>{};loadDeckIDB=async()=>false;loadDeckFromFirebase=cb=>cb(false);loadDeck=()=>{};loadScore=()=>{};loadNames=()=>{};loadOrder=()=>{};
 const originalSend=sendState;sendState=function(){if(!ready||restoring)return;originalSend();if(V.host&&currentCard()&&String(currentCard().id)!==lastCard)serial(async()=>{await ensureCard();schedule()})};
 markCorrect=()=>serial(async()=>{const g=game(),who=g.active;if(!who)throw Error('No hay equipo con turno confirmado');await V.act({type:'verdict',sessionId:g.id,ok:true});sync();sendState();gmsCelebrate(V.name(who),V.s.settings.games.movies.points)});markWrong=V.handlers['native-wrong'];setBuzzer=()=>V.toast('El turno se confirma desde el buzzer del celular');adjScore=(t,d)=>V.handlers['native-score'](game().teamIds[t==='a'?0:1],d);
 startTimer=()=>{const g=game();if(!g.active)return g.queue.length&&!g.verdict?.ok?V.handlers['native-retry']():serial(open);return V.action({type:'timer',sessionId:g.id,command:g.timer&&!g.timer.running?'resume':'start',seconds:timerDefault})};stopTimer=()=>{};resetTimer=()=>V.action({type:'timer',sessionId:game().id,command:'reset'});adjTimer=d=>V.run(async()=>{timerDefault=Math.max(5,Math.min(120,timerDefault+d));const games=V.M.copy(V.s.settings.games);games.movies.seconds=timerDefault;await V.act({type:'settings',values:{games}});V.toast('Próximo temporizador: '+timerDefault+' segundos')});
 const oldRenderCond=renderCondCard;renderCondCard=function(){oldRenderCond();const c=currentCard();if(c?.bonusOptions?.length&&!bonusRevealed){document.querySelectorAll('.bonus-team-btn').forEach(e=>e.remove());const row=document.querySelector('.cond-bonus-row');if(row)row.insertAdjacentHTML('beforeend',game().teamIds.map(t=>`<button class="cta-btn bonus-team-btn" onclick="bonusAnswer('${t}')">✓ Acertó ${V.esc(V.name(t))}</button>`).join(''))}};
 bonusAnswer=team=>serial(async()=>{if(bonusRevealed)return;const card=currentCard();if(!card?.bonusOptions?.length)return;if(team){if(!game().teamIds.includes(team))throw Error('Equipo inexistente');await V.act({type:'score',sessionId:game().id,teamId:team,value:(game().scores[team]||0)+1})}bonusRevealed=true;bonusAwardTeam=team||null;renderCondCard();sendState();V.toast(team?'🎯 +1 · '+V.name(team):'Nadie acertó');_bonusAdvanceTimer=setTimeout(()=>{_bonusAdvanceTimer=null;passCard()},2200)});
 const oldToggle=toggleReveal;toggleReveal=function(){oldToggle();if(!revealed)V.action({type:'lockBuzzer',sessionId:game().id});schedule()};
 resetGame=()=>confirm('¿Reiniciar marcador y partida? Se conserva el resultado del ranking hasta corregirlo.')&&V.run(async()=>{await V.store.native(game().id,null);await V.act({type:'resetSession',id:game().id});loaded='';await boot()});openNameEditor=()=>V.toast('Los nombres y fotos se editan en Equipos, desde el panel.');
 }else if(k==='qld'){
 fbPushLive=()=>schedule();fbPushDeck=()=>V.run(()=>V.store.saveDeck(k,deck));saveDeckLocal=()=>{if(ready)V.run(()=>V.store.saveDeck(k,deck))};saveTeamScores=()=>{};fbOpenBuzzer=()=>serial(open);fbLockBuzzer=()=>{};fbSendVerdict=()=>{};toggleBuzzer=()=>serial(async()=>{if(['open','answering'].includes(game().status))await V.act({type:'lockBuzzer',sessionId:game().id});else await open();sync();schedule()});saveIdx=()=>{if(ready)serial(async()=>{await ensureCard();schedule()})};
 doAssign=index=>serial(async()=>{const g=game(),id=g.teamIds[index],amount=Number(assignAmount||1);if(!id)throw Error('Equipo inexistente');if(g.status==='answering'){if(g.active!==id)throw Error('Solo puede responder el equipo con turno confirmado');await V.act({type:'verdict',sessionId:g.id,ok:true,points:amount})}else throw Error('Abrí el buzzer y esperá un turno confirmado');revealed=true;renderCard();closeAssign();celebrateScore(V.name(id),amount);sync();schedule()});finalizeRound=()=>V.finish();resetScores=()=>V.toast('Reiniciá la partida desde el panel.');openPlayers=()=>V.toast('Los equipos se administran desde Equipos.');
 }else if(k==='argentinos'){
 writeSync=schedule;saveScore=()=>{};startRoundTimer=()=>{};stopRoundTimer=()=>{};fbLock=()=>{};fbSendControl=()=>{};fbToggle=()=>serial(async()=>{if(['open','answering'].includes(game().status))await V.act({type:'lockBuzzer',sessionId:game().id});else await open();sync();schedule()});saveBank=()=>{if(ready)V.run(()=>V.store.saveDeck(k,bank))};
 const oldLaunch=_launchRound;_launchRound=function(members){oldLaunch(members);serial(async()=>{await V.act({type:'next',sessionId:game().id,index:0,card:{q:round.q,count:round.a.length},questionId:V.M.id()});await V.store.native(game().id,native());sync();schedule()})};
 buzz=()=>V.toast('El orden se confirma desde los celulares.');tapSlot=i=>serial(async()=>{const g=game();if(!round||!round.a[i])return;await V.act({type:'revealSurvey',sessionId:g.id,index:i,text:round.a[i].t,points:round.a[i].v,total:round.a.length});playRevealDing(i+1,.7);sync();schedule()});doStrike=()=>serial(async()=>{await V.act({type:'verdict',sessionId:game().id,ok:false});playBuzzer();sync();schedule()});chooseControl=opt=>opt==='pasar'?V.action({type:'surveyPass',sessionId:game().id}):null;undoReveal=()=>V.action({type:'sessionUndo',sessionId:game().id});undoStrike=undoReveal;
 addPoint=(side,delta)=>serial(async()=>{const g=game(),s={a:g.sideScores?.a||0,b:g.sideScores?.b||0};s[side]=Math.max(0,s[side]+delta);await V.act({type:'sideScores',sessionId:g.id,...s});sync();schedule()});resetScore=()=>V.toast('Reiniciá la partida desde el panel.');saveNames=()=>V.toast('Las agrupaciones se editan desde el panel.');setMult=()=>V.toast('El pozo usa los valores de las respuestas, sin multiplicador adicional.');surrender=()=>V.toast('Usá los strikes y el único intento de robo para resolver la ronda.');
 const oldFmRender=fmRender;fmRender=function(){oldFmRender();schedule()};const oldClose=closeRound;closeRound=function(){oldClose();schedule()};
 }else{
 const oldSaveState=saveState;saveState=function(){oldSaveState();schedule()};saveScore=()=>{if(ready)serial(async()=>{const g=game();await V.act({type:'scores',sessionId:g.id,scores:{[g.teamIds[0]]:score.a,[g.teamIds[1]]:score.b}});schedule()})};saveDeck=()=>{if(ready)V.run(()=>V.store.saveDeck(k,deck))};saveNames=()=>V.toast('Los nombres se administran desde Equipos.');
 }
document.querySelectorAll('[onclick="applyMode(\'participant\')"]').forEach(e=>e.onclick=()=>{location.href=location.pathname+'?mode=tv'+(V.g?'&partida='+V.g.id:'')});
if(typeof gateConductor==='function')gateConductor=()=>V.run(async()=>{if(V.store.db&&!V.store.authorized)await V.store.login();await boot()});if(typeof gateCheckPass==='function')gateCheckPass=gateConductor;
V.on(()=>{if(V.g?.id!==loaded)boot();else sync()});V.ready.then(boot);setInterval(()=>{if(!ready||!V.host)return;if(k==='movies'){if(guessView&&V.g?.timer){const t=V.g.timer;timerLeft=Math.ceil(Math.max(0,t.running?t.endAt-V.store.now():t.remaining)/1000)}syncTimerUI()}else if(k==='argentinos'&&round&&V.g?.timer){const t=V.g.timer,sec=Math.ceil(Math.max(0,t.running?t.endAt-V.store.now():t.remaining)/1000);const e=$('rt-secs');if(e){e.textContent=sec;$('round-timer').style.display='flex'}}if(k==='qld'||k==='palabras')schedule()},500);
})();
