/* All original screens share this transport and the pure team model. */
(function(){'use strict';const M=VeladaModel,copy=M.copy;
const loaders=new Map();function load(src){if(!loaders.has(src))loaders.set(src,new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(Error('No se pudo cargar Firebase'));document.head.append(s)}));return loaders.get(src)}
class Store{
 constructor(_,host){Object.assign(this,{id:'principal',host,root:'velada/equipos2026',key:VELADA_STORAGE_PREFIX+':principal',listeners:[],deckCache:{},state:null,db:null,online:false,ready:false,authorized:!!(host&&window.VeladaAccess?.unlocked()),status:'connecting',offset:0,epoch:0,pending:new Map(),chain:Promise.resolve()})}
 now(){return Date.now()+this.offset}on(fn){this.listeners.push(fn);if(this.state)fn(this.state);return()=>this.listeners=this.listeners.filter(x=>x!==fn)}emit(){for(const fn of this.listeners)fn(this.state,this.status)}save(s){try{localStorage.setItem(this.key,JSON.stringify(s))}catch{}}
 async init(seed){try{this.state=JSON.parse(localStorage.getItem(this.key)||'null')}catch{}if(this.state)this.state=M.normalize(this.state);if(!this.state&&seed)this.state=seed;this.emit();try{
 await load('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');await load('https://www.gstatic.com/firebasejs/10.12.2/firebase-database-compat.js');const name=this.host?'velada-v3-conductor':'velada-v3-public';this.app=firebase.apps.find(a=>a.name===name)||firebase.initializeApp(VELADA_FIREBASE_CONFIG,name);this.db=this.app.database();this.ref=this.db.ref(this.root+'/state');
 this.db.ref('.info/serverTimeOffset').on('value',s=>this.offset=Number(s.val()||0));this.db.ref('.info/connected').on('value',s=>{const was=this.online;this.online=s.val()===true;if(was&&!this.online)this.epoch++;this.status=this.online?'online':'reconnecting';this.emit()});
 this.ref.on('value',snap=>{this.state=snap.exists()?M.normalize(snap.val()):(this.host?M.create('La Velada del Año','principal'):null);if(this.state)this.save(this.state);this.ready=true;this.applyPhotos();this.emit()},e=>{this.status='error: '+e.message;this.ready=false;this.emit()});
 this.db.ref(this.root+'/wallInbox').on('value',snap=>{this.wallInbox=snap.val()||{};this.emit()});
 if(this.host&&this.authorized)await this.ref.transaction(s=>s||copy(seed||M.create('La Velada del Año','principal')),undefined,false);
 this.initPhotos().catch(e=>{this.photosError=e.message;this.emit()});
 }catch(e){this.lastError=e.message;this.status=this.db?'error: '+e.message:'local';this.ready=!this.db;if(this.state)this.save(this.state);this.emit()}return this}
 async login(code){if(!window.VeladaAccess.valid(code))throw Error('Contraseña incorrecta, intentá de nuevo.');window.VeladaAccess.remember();this.authorized=!!this.host;this.emit();}
 applyPhotos(){if(!this.state)return;const photos=this.photoLibrary||{};this.state.photos={...this.state.photos,...photos};for(const p of this.state.participants){const match=Object.keys(photos).find(n=>this.photoKey(n)===this.photoKey(p.name));if(match)p.photo=photos[match]}}
 photoKey(name){return String(name||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
 async initPhotos(){await load('https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore-compat.js');const name='velada-original-fotos';const app=firebase.apps.find(a=>a.name===name)||firebase.initializeApp(VELADA_PHOTOS_CONFIG,name);this.fs=app.firestore();window._fbRead=async key=>{if(key==='state')return null;const snap=await this.fs.collection('ndj').doc(key).get();return snap.exists?snap.data().data:null};window._fbReadMeta=async key=>{if(key==='state')return null;const snap=await this.fs.collection('ndj').doc(key).get();return snap.exists?snap.data():null};window._fbWrite=async(key,data)=>{if(key==='state')return;this.requireHost();await this.fs.collection('ndj').doc(key).set({data:String(data),ts:Date.now()})};window._fbReady=true;this.fs.collection('ndj').doc('photos').onSnapshot(snap=>{try{this.photoLibrary=JSON.parse(snap.exists?snap.data().data:'{}');if(typeof this.photoLibrary!=='object'||Array.isArray(this.photoLibrary))this.photoLibrary={};this.applyPhotos();if(this.host&&typeof window.applyOriginalPhotos==='function')window.applyOriginalPhotos(this.photoLibrary);this.emit()}catch(e){this.photosError=e.message}})}
 async rememberPhoto(name,url){this.requireHost();if(this.fs){await this.fs.runTransaction(async tx=>{const ref=this.fs.collection('ndj').doc('photos'),snap=await tx.get(ref);let photos={};try{photos=JSON.parse(snap.exists?snap.data().data:'{}')}catch{}if(url)photos[name]=url;else delete photos[name];const data=JSON.stringify(photos);if(data.length>=1000000)throw Error('La biblioteca de fotos superó el límite del documento original');tx.set(ref,{data,ts:Date.now()})})}else{this.photoLibrary=this.photoLibrary||{};if(url)this.photoLibrary[name]=url;else delete this.photoLibrary[name];await this.dispatch({type:'photo',name,url})}}
 requireHost(){if(!this.host)throw Error('Acción del conductor');if(!this.authorized)throw Error('Ingresá la contraseña del conductor')}
 async dispatch(a){a={...a,operationId:a.operationId||M.id()};if(a.type==='buzz')return this.buzz(a);if(a.type==='submit')return this.answer(a);this.requireHost();if(this.db){if(!this.online||!this.ready)throw Error('Sin conexión: no se guardó la acción');let problem;const r=await this.ref.transaction(cur=>{try{return M.reduce(cur||M.create('La Velada del Año','principal'),a,this.now())}catch(e){problem=e;return}},undefined,false);if(!r.committed)throw problem||Error('No se confirmó la acción');return this.state}const run=()=>{this.state=M.reduce(this.state,a,this.now());this.save(this.state);this.emit();return this.state};this.chain=this.chain.catch(()=>{}).then(run);return this.chain}
 async buzz(a){if(!this.db||!this.ready||!this.online||this.status!=='online')throw Error('El buzzer necesita conexión a Firebase');const key=a.sessionId+':'+a.questionId+':'+a.teamId;if(this.pending.has(key))return this.pending.get(key);const epoch=this.epoch;const work=(async()=>{let err;const r=await this.db.ref(this.root+'/state/sessions/'+a.sessionId+'/buzzer').transaction(cur=>{if(!this.online||epoch!==this.epoch){err=Error('La conexión se cortó. Volvé a pulsar al reconectar.');return}if(cur===null)return;try{const next=M.reduceBuzzSession(cur,{...a,eligible:this.state.sessions[a.sessionId].eligibleTeams,groups:this.state.sessions[a.sessionId].groups},this.now());if(next.queueText===cur.queueText)return;next.pressTeam=a.teamId;next.pressPlayer=a.playerId||'';next.pressedAt=firebase.database.ServerValue.TIMESTAMP;return next}catch(e){err=e;return}},undefined,false);if(!r.committed)throw err||Error('Tu equipo ya pulsó o cambió la pregunta');return r.snapshot.val()})();this.pending.set(key,work);try{return await work}finally{this.pending.delete(key)}}
 async answer(a){if(!this.db||!this.ready||!this.online)throw Error('Esperá la conexión para responder');const g=this.state?.sessions[a.sessionId];if(!g||g.questionId!==a.questionId||g.status!=='open'||!g.teamIds.includes(a.teamId)||!Number.isFinite(a.value)||!g.timer?.running||g.timer.endAt<=this.now())throw Error('La respuesta no está habilitada');const r=await this.db.ref(this.root+'/state/sessions/'+a.sessionId+'/answers/'+a.teamId).transaction(v=>v?undefined:{value:a.value,at:firebase.database.ServerValue.TIMESTAMP,questionId:a.questionId,playerId:a.playerId||localStorage.getItem('velada-v3:player')||''},undefined,false);if(!r.committed)throw Error('Tu equipo ya respondió')}
 async deck(game){if(Object.prototype.hasOwnProperty.call(this.deckCache,game))return this.deckCache[game];let cards=await idbGet(this.key+':deck:'+game);if(cards===undefined)cards=copy(VELADA_INITIAL_DECKS[game]||[]);if(this.db&&this.online&&this.authorized){const d=(await this.db.ref(this.root+'/decks/'+game).once('value')).val();if(d?.initialized)cards=M.arr(d.cards);else if(cards.length&&['movies','qld'].includes(game)){const old=(await this.db.ref(game==='movies'?'velada/deck':'velada/qld/deck').once('value')).val();if(Array.isArray(old?.cards||old?.deck))cards=copy(old.cards||old.deck)}}return this.deckCache[game]=cards}
 async saveDeck(game,cards){this.requireHost();if(!Array.isArray(cards))throw Error('Mazo inválido');const data=copy(cards.map(c=>typeof c==='string'?{id:M.id(),name:c}:({...c,id:c.id??M.id()})));if(this.db){if(!this.online)throw Error('Sin conexión: no se guardó el mazo');await this.db.ref(this.root+'/decks/'+game).set({initialized:true,cards:data})}await idbSet(this.key+':deck:'+game,data);return this.deckCache[game]=data}
 async native(id,value){this.requireHost();if(this.db){if(!this.online)throw Error('Sin conexión: no se guardó el juego');await this.db.ref(this.root+'/native/'+id).set(copy(value))}else await idbSet(this.key+':native:'+id,value)}
 async readNative(id){this.requireHost();return this.db?(await this.db.ref(this.root+'/native/'+id).once('value')).val():await idbGet(this.key+':native:'+id)}
 async publish(id,value){this.requireHost();if(this.db){if(!this.online)throw Error('Sin conexión: no se publicó la pantalla');await this.db.ref(this.root+'/live/'+id).set(copy(value))}}
 watchLive(id,fn){if(!this.db)return()=>{};const r=this.db.ref(this.root+'/live/'+id);r.on('value',s=>fn(s.val()));return()=>r.off()}
 async wallPost(post){if(this.host)return this.dispatch({type:'wallPost',...post});if(!this.db||!this.online)throw Error('Sin conexión');if(!post.text?.trim()&&!post.photo)throw Error('Escribí un mensaje o adjuntá una foto');await this.db.ref(this.root+'/wallInbox').push({...post,at:firebase.database.ServerValue.TIMESTAMP});}
 async restore(data){this.requireHost();validateBackup(data);const s=copy(data.state);s.id='principal';for(const g of Object.values(s.sessions||{}))if(g.game==='impostor'){g.status='closed';g.timer=null}if(this.db){if(!this.online)throw Error('Sin conexión');const updates={state:M.normalize(s),native:data.native||null,live:null,wallInbox:null};for(const [game,cards]of Object.entries(data.decks||{}))updates['decks/'+game]={initialized:true,cards};await this.db.ref(this.root).update(updates)}else{this.state=M.normalize(s);this.save(s);this.emit()}for(const [id,n]of Object.entries(data.native||{}))await idbSet(this.key+':native:'+id,n);for(const [g,c]of Object.entries(data.decks||{})){await idbSet(this.key+':deck:'+g,c);this.deckCache[g]=c}}
}
function validateBackup(d){if(d?.version!==2||d.state?.version!==2)throw Error('Respaldo incompatible');const s=d.state,known={...M.GAMES,...s.customGames};if(!Array.isArray(s.teams)||!Array.isArray(s.participants)||!Array.isArray(s.fixture))throw Error('Roster o fixture inválido');const ids=new Set();for(const t of s.teams){if(!t.id||/[.#$\[\]\/|]/.test(t.id)||ids.has(t.id)||typeof t.name!=='string')throw Error('Equipos inválidos');ids.add(t.id)}const players=new Set();for(const p of s.participants){if(!p.id||players.has(p.id)||typeof p.name!=='string'||p.teamId&&!ids.has(p.teamId))throw Error('Participantes inválidos');players.add(p.id)}for(const r of Object.values(s.results||{}))for(const [id,v]of Object.entries(r.points||{}))if(!ids.has(id)||!Number.isFinite(v))throw Error('Resultado inválido');for(const [g,c]of Object.entries(d.decks||{})){if(!(g in known)||!Array.isArray(c))throw Error('Mazo inválido');if(window.VeladaValidateDeck)VeladaValidateDeck(g,c)}for(const id of Object.keys(d.native||{}))if(!s.sessions?.[id]||s.sessions[id].game==='impostor')throw Error('Estado privado incompatible');for(const g of [...s.fixture,...Object.values(s.sessions||{})])if(!(g.game in known)||!Array.isArray(g.teamIds)||g.teamIds.some(id=>!ids.has(id)))throw Error('Partida inválida')}
let promise;function idb(){return promise||(promise=new Promise((res,rej)=>{const r=indexedDB.open('velada-v3-media',1);r.onupgradeneeded=()=>r.result.createObjectStore('kv');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}))}async function idbGet(key){const db=await idb();return new Promise((res,rej)=>{const r=db.transaction('kv').objectStore('kv').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function idbSet(key,value){const db=await idb();return new Promise((res,rej)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(value,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
window.VeladaStore=Store;window.VeladaValidateBackup=validateBackup;
})();
