/* Core v2: pure, deterministic operations; stable IDs and result replacement. */
(function(root){'use strict';
const GAME_DEFS={movies:{name:'Guess Movies/Songs',mode:'sim',seconds:15},qld:{name:'Quién lo dijo',mode:'sim',seconds:20},erudito:{name:'El Erudito',mode:'sim',seconds:60},impostor:{name:'El Impostor',mode:'sim',seconds:900},times:{name:"Time’s Up",mode:'duel',seconds:60},beer:{name:'Beer Pong',mode:'duel',seconds:900},mario:{name:'Mario Party',mode:'special',seconds:0},argentinos:{name:'100 Argentinos Dicen',mode:'special',seconds:40},palabras:{name:'Palabras a Tiempo',mode:'duel',seconds:60},curling:{name:'Curling',mode:'duel',seconds:0},mentes:{name:'Carrera de Mentes',mode:'duel',seconds:0}};
const GAMES=Object.fromEntries(['movies','argentinos','qld','erudito','impostor','palabras','mario','beer','times','curling','mentes'].map(k=>[k,GAME_DEFS[k]]));
const copy=x=>JSON.parse(JSON.stringify(x));
const id=()=> 'id_'+(root.crypto?.randomUUID?.()||Date.now().toString(36)+'_'+Math.random().toString(36).slice(2));
const assert=(ok,message)=>{if(!ok)throw Error(message);};
const arr=x=>Array.isArray(x)?x:[];
function normalize(s){for(const k of Object.keys(GAMES))if(!GAME_DEFS[k])delete GAMES[k];Object.assign(GAMES,s.customGames||{});s.teams=arr(s.teams);s.participants=arr(s.participants);s.fixture=arr(s.fixture);s.columns=arr(s.columns);s.results=s.results||{};s.sessions=s.sessions||{};s.history=arr(s.history);s.sessionHistory=s.sessionHistory||{};s.wall=arr(s.wall);s.photos=s.photos||{};s.playerTeams=Object.fromEntries(s.participants.filter(p=>p.teamId).map(p=>[p.id,p.teamId]));s.presentation=s.presentation||{mode:'none',index:0};s.processed=arr(s.processed);s.groups=s.groups||{a:{name:'Agrupación 1',teams:[]},b:{name:'Agrupación 2',teams:[]}};for(const x of Object.values(s.groups))x.teams=arr(x.teams);s.settings=s.settings||{};s.settings.games=s.settings.games||{};Object.entries(GAMES).forEach(([k,g])=>s.settings.games[k]=Object.assign({seconds:g.seconds,points:1,rounds:1,target:0,station:k,enabled:true},s.settings.games[k]||{}));Object.values(s.sessions).forEach(g=>{normalizeSession(g);g.teamIds=arr(g.teamIds);g.queue=arr(g.queue);g.failed=arr(g.failed);g.revealed=arr(g.revealed);g.caught=arr(g.caught);g.eliminated=arr(g.eliminated);g.playerIds=arr(g.playerIds);g.scores=g.scores||{};g.answers=g.answers||{};});if(s.bracket){s.bracket.rounds=arr(s.bracket.rounds);s.bracket.rounds.forEach(r=>r.matches=arr(r.matches));s.bracket.seeds=arr(s.bracket.seeds)}return s;}
function create(name,eventId=id()){return normalize({version:2,id:eventId,name:name||'Nueva velada',createdAt:Date.now(),revision:0,teams:[],participants:[],columns:Object.entries(GAMES).filter(([k,g])=>GAME_DEFS[k]).map(([k,g])=>({id:k,name:g.name})),settings:{games:{},duelRepeats:1,marioPrizes:[3,2,1],stealSeconds:40,thirdPlace:false,bracketGames:['London 2012','Mario Party','Mario Kart 8','Keep Talking and Nobody Explodes'],bracketConditions:{},impostorPolicy:'manual'},results:{},fixture:[],sessions:{},history:[],closed:false,presentation:{mode:'none',index:0},photos:{},impUsed:[]});}
function autoGroups(s){const ids=s.teams.map(t=>t.id);assert(ids.length>=2,'Creá al menos dos equipos');const weights=Object.fromEntries(ids.map(t=>[t,Math.max(1,s.participants.filter(p=>p.teamId===t).length)])),people=ids.reduce((n,t)=>n+weights[t],0),ordered=ids.slice().sort((a,b)=>weights[b]-weights[a]);let best=null,bestScore=Infinity;for(let count=2;count<=ids.length;count++){const buckets=Array.from({length:count},(_,i)=>({key:i<26?String.fromCharCode(97+i):'grupo_'+(i+1),name:'Grupo '+(i+1),teams:[],size:0}));for(const t of ordered){const target=buckets.slice().sort((a,b)=>a.size-b.size||a.teams.length-b.teams.length)[0];target.teams.push(t);target.size+=weights[t]}const mean=people/count,spread=Math.sqrt(buckets.reduce((n,g)=>n+(g.size-mean)**2,0)/count),single=buckets.filter(g=>g.teams.length===1).length/count,score=2*spread+Math.abs(mean-4)+2*single;if(score<bestScore-1e-9){bestScore=score;best=Object.fromEntries(buckets.map(g=>[g.key,{name:g.name,teams:g.teams}]))}}return best;}

function validateGroups(s){const all=Object.values(s.groups).flatMap(g=>g.teams);assert(Object.values(s.groups).filter(g=>g.teams.length).length>=2,'Armá al menos dos agrupaciones');assert(new Set(all).size===all.length,'Una dupla no puede quedar repartida');assert(all.length===s.teams.length&&s.teams.every(t=>all.includes(t.id)),'Incluí todos los equipos completos');}
function groupRanking(scores){const entries=Object.entries(scores),counts={};entries.forEach(([k,v])=>counts[v]=(counts[v]||0)+1);const ties=entries.filter(([k,v])=>counts[v]>1).map(([k])=>k);if(ties.length)return Object.fromEntries(entries.map(([k])=>[k,ties.includes(k)?1:0]));return Object.fromEntries(entries.sort((a,b)=>b[1]-a[1]).map(([k],i)=>[k,i===0?3:i===1?1:0]));}

function standings(s){return s.teams.map(t=>{const cells=Object.fromEntries(s.columns.map(c=>[c.id,0]));Object.values(s.results).forEach(r=>{if(r.columnId in cells)cells[r.columnId]+=Number(r.points?.[t.id]||0)});return {...t,cells,total:Object.values(cells).reduce((a,b)=>a+b,0)}}).sort((a,b)=>b.total-a.total||a.order-b.order);}
function result(s,r){assert(!s.closed,'El ranking está cerrado; reabrilo antes de corregir');assert(s.columns.some(c=>c.id===r.columnId),'Columna inexistente');assert(r.id,'Falta identidad del resultado');Object.entries(r.points||{}).forEach(([t,p])=>{assert(s.teams.some(x=>x.id===t),'Equipo inexistente');assert(Number.isFinite(p),'Puntaje inválido')});const before=s.results[r.id]||null;const after={...copy(r),updatedAt:r.updatedAt||Date.now()};s.results[r.id]=after;s.history.push({id:r.id,before,after});s.history=s.history.slice(-100);return s;}
function awardScores(scores,teams,mode,prizes=[3,2,1],placements){const pts=Object.fromEntries(teams.map(t=>[t,0]));if(mode==='mario'){assert(placements?.length,'Definí el podio de Mario');assert(new Set(placements).size===placements.length,'Podio repetido');placements.forEach((t,i)=>{assert(t in pts,'Equipo fuera de la etapa');pts[t]=Number(prizes[i]||0)});return pts;}const vals=teams.map(t=>Number(scores[t]||0)),max=Math.max(...vals),winners=teams.filter((t,i)=>vals[i]===max);winners.forEach(t=>pts[t]=winners.length===1?3:1);return pts;}
function circlePairs(teamIds){const ids=[...teamIds];if(ids.length%2)ids.push(null);const rounds=[];for(let r=0;r<ids.length-1;r++){rounds.push(Array.from({length:ids.length/2},(_,i)=>[ids[i],ids[ids.length-1-i]]).filter(p=>p.every(Boolean)));ids.splice(1,0,ids.pop())}return rounds;}
function makeFixture(s,repeats=1){assert(!s.fixture.length,'El fixture ya existe. Eliminá explícitamente los encuentros pendientes antes de generar otro');assert(s.teams.length>=2,'Creá al menos dos equipos');assert(Number.isInteger(repeats)&&repeats>=1&&repeats<=10,'Repeticiones entre 1 y 10');let round=1;const out=[];const teams=s.teams.map(t=>t.id);for(const [game,g] of Object.entries(GAMES)){if(!s.settings.games[game].enabled)continue;if(g.mode==='sim'||g.mode==='manual')out.push({id:id(),round:round++,game,teamIds:teams.slice(),station:s.settings.games[game].station});if(g.mode==='duel'){for(let n=0;n<repeats;n++){const pairs=circlePairs(teams);for(const rs of pairs){/* A single physical station cannot host two matches concurrently. */for(const pair of rs)out.push({id:id(),round:round++,game,teamIds:pair,station:s.settings.games[game].station})}}}if(g.mode==='special')out.push({id:id(),round:round++,game,teamIds:teams.slice(),station:s.settings.games[game].station});}s.fixture=out;s.settings.duelRepeats=repeats;return s;}
function fixtureAudit(s){const errors=[];const counts=Object.fromEntries(s.teams.map(t=>[t.id,{}]));const rounds={};s.fixture.forEach(m=>{const r=rounds[m.round]||(rounds[m.round]={teams:new Set(),stations:new Set()});if(r.stations.has(m.station))errors.push('Ronda '+m.round+': estación repetida '+m.station);r.stations.add(m.station);m.teamIds.forEach(t=>{if(!counts[t]){errors.push('Encuentro con equipo eliminado: '+m.id);return}if(r.teams.has(t))errors.push('Ronda '+m.round+': equipo simultáneo '+t);r.teams.add(t);counts[t][m.game]=(counts[t][m.game]||0)+1;})});const differences=[];Object.keys(GAMES).forEach(game=>{const a=Object.values(counts).map(c=>c[game]||0);if(a.length&&Math.min(...a)!==Math.max(...a))differences.push(game)});return {errors,counts,differences,maxPoints:Object.fromEntries(Object.entries(counts).map(([t,c])=>[t,Object.fromEntries(Object.entries(c).map(([g,n])=>[g,3*n]))]))};}
function seedOrder(n){let x=[1,2];while(x.length<n){const sum=x.length*2+1;x=x.flatMap(v=>[v,sum-v])}return x;}
function makeBracket(s,seeds){assert(s.closed,'Cerrá el ranking antes de generar el cuadro');assert(!s.bracket,'El cuadro ya existe');const ranking=standings(s);assert(ranking.length>=2,'Necesitás dos equipos');assert(ranking.length<=128,'Máximo 128 equipos por cuadro');const sorted=seeds||ranking.map(t=>t.id);assert(sorted.length===ranking.length&&new Set(sorted).size===ranking.length&&sorted.every(t=>ranking.some(r=>r.id===t)),'Orden de clasificación inválido');for(let i=1;i<sorted.length;i++){const a=ranking.find(t=>t.id===sorted[i-1]),b=ranking.find(t=>t.id===sorted[i]);assert(a.total>=b.total,'El desempate no puede cambiar posiciones con distinto puntaje');}let size=2;while(size<sorted.length)size*=2;const labels={128:'Ronda de 128',64:'Ronda de 64',32:'Ronda de 32',16:'Octavos',8:'Cuartos',4:'Semifinales',2:'Final'};const rounds=[];let current=size;while(current>=2){rounds.push({name:labels[current],game:current>16?(s.settings.preliminaryGame||s.settings.bracketGames[0]):s.settings.bracketGames[4-Math.log2(current)],matches:Array.from({length:current/2},()=>({id:id(),a:null,b:null,winner:null,bye:false,score:null}))});current/=2;}const slots=seedOrder(size).map(rank=>sorted[rank-1]||null);rounds[0].matches.forEach((m,i)=>{m.a=slots[i*2];m.b=slots[i*2+1];if(!m.a||!m.b){m.winner=m.a||m.b;m.bye=true}});s.bracket={seeds:sorted,rounds,champion:null,third:null};propagate(s.bracket);return s;}
function propagate(b){for(let r=0;r<b.rounds.length-1;r++){const cur=b.rounds[r].matches,next=b.rounds[r+1].matches;next.forEach((m,i)=>{const a=cur[i*2].winner,b=cur[i*2+1].winner;if(m.a!==a||m.b!==b){m.a=a;m.b=b;m.winner=null;m.score=null;}})}const final=b.rounds.at(-1).matches[0];b.champion=final.winner||null;}
function recordBracket(s,matchId,winner,score){assert(s.bracket,'No hay cuadro');const m=s.bracket.rounds.flatMap(r=>r.matches).find(m=>m.id===matchId);assert(m&&!m.bye&&m.a&&m.b,'Cruce incompleto o pase directo');assert([m.a,m.b].includes(winner),'Ganador inválido');m.winner=winner;m.score=score||'';propagate(s.bracket);return s;}
function startSession(s,match,now){assert(!s.sessions[match.id],'El encuentro ya está iniciado');assert(!s.closed||match.exhibition,'El ranking está cerrado');assert(match.teamIds.every(t=>s.teams.some(x=>x.id===t)),'Corregí los equipos del encuentro');Object.values(s.sessions).filter(g=>!['done','closed'].includes(g.status)&&g.id!==match.id).forEach(g=>assert(!g.teamIds.some(t=>match.teamIds.includes(t)),'Ese equipo ya tiene un juego activo'));if(match.game==='argentinos')validateGroups(s);s.sessions[match.id]=normalizeSession({id:match.id,game:match.game,teamIds:match.teamIds.slice(),eligibleTeams:Object.fromEntries(match.teamIds.map(t=>[t,true])),eligibleSides:Object.fromEntries(match.teamIds.map(t=>[t,match.game==='argentinos'?(Object.keys(s.groups).find(k=>s.groups[k].teams.includes(t))):t])),status:'ready',questionId:id(),cardIndex:0,scores:Object.fromEntries(match.teamIds.map(t=>[t,0])),queue:[],failed:[],active:null,timer:null,answers:{},strikes:0,pot:0,revealed:[],round:0,verdict:null,groups:match.game==='argentinos'?copy(s.groups):null,surveyPhase:match.game==='argentinos'?'faceoff':null,groupStrikes:{},sideScores:match.game==='argentinos'?Object.fromEntries(Object.keys(s.groups).map(k=>[k,0])):null,faceoffRanks:{},faceoffAttempted:[],multiplier:1,impRoundStart:match.game==='impostor'?(s.legacy?.impostor?.rounds?.length||0):null,mario:null,createdAt:now});return s;}
const BUZZ_KEYS=['questionId','status','active','steal','control','originalControl','buzzSeconds','surveyPhase'];
function buzzerState(g){const out={id:g.id,game:g.game,buzzRevision:g.buzzer?.buzzRevision||g.buzzRevision||0,queueText:'|'+arr(g.queue).map(x=>x+'|').join(''),failedText:'|'+arr(g.failed).map(x=>x+'|').join('')};for(const k of BUZZ_KEYS)if(g[k]!=null)out[k]=copy(g[k]);if(g.timer)Object.assign(out,{timerToken:g.timer.token,timerEndAt:g.timer.endAt,timerRemaining:g.timer.remaining,timerRunning:g.timer.running});return out;}
function normalizeSession(g){if(g.buzzer){for(const k of BUZZ_KEYS)g[k]=g.buzzer[k]??null;g.queue=(g.buzzer.queueText||'').split('|').filter(Boolean);g.failed=(g.buzzer.failedText||'').split('|').filter(Boolean);g.timer=g.buzzer.timerToken?{token:g.buzzer.timerToken,endAt:g.buzzer.timerEndAt,remaining:g.buzzer.timerRemaining,running:g.buzzer.timerRunning}:null;}g.queue=arr(g.queue);g.failed=arr(g.failed);g.answers=g.answers||{};g.revealed=arr(g.revealed);g.eliminated=arr(g.eliminated);g.caught=arr(g.caught);g.playerIds=arr(g.playerIds);return g;}
function startTimer(g,seconds,now){assert(Number.isFinite(seconds)&&seconds>0&&seconds<=7200,'Duración entre 1 y 7200 segundos');g.timer={token:id(),endAt:now+seconds*1000,remaining:seconds*1000,running:true};}
function responseSeconds(s,g){return g.game==='argentinos'&&g.steal?s.settings.stealSeconds:s.settings.games[g.game].seconds;}
function assignNext(s,g,now){g.active=null;const next=g.queue.find(t=>!g.failed.includes(t));if(next){g.active=next;g.status='answering';if(g.game==='argentinos')g.control=next;if(g.game==='argentinos'&&g.surveyPhase==='faceoff')g.timer=null;else startTimer(g,responseSeconds(s,g),now);}else{g.status='open';g.timer=null;}}
function sideFor(s,g,teamId){if(g.game!=='argentinos')return teamId;return Object.keys(g.groups||{}).find(k=>g.groups[k].teams.includes(teamId))||null;}
function buzz(s,g,teamId,questionId,now){assert(g.game!=='argentinos'||g.surveyPhase==='faceoff','El tablero ya empezó');assert(g.questionId===questionId,'La pregunta cambió');assert(['open','answering'].includes(g.status),'Buzzer cerrado');assert(g.teamIds.includes(teamId),'Tu equipo no participa');const side=sideFor(s,g,teamId);assert(side,'Equipo sin agrupación');if(g.failed.includes(side)||g.queue.includes(side)||g.steal)return s;g.queue.push(side);if(!g.active)assignNext(s,g,now);return s;}
// Same arbitration as the full reducer, with only the active session on the wire.
function reduceBuzzSession(input,a,now=Date.now()){
 assert(input,'Partida inexistente');const g=normalizeSession({id:input.id,game:input.game,buzzer:copy(input),teamIds:Object.keys(a.eligible||{}),groups:a.groups||null});delete g.buzzer;
 assert(['movies','qld','argentinos'].includes(g.game),'Este juego no tiene buzzer');
 const seconds=Number(g.buzzSeconds||GAMES[g.game].seconds),context={settings:{stealSeconds:40,games:{[g.game]:{seconds}}}};
 buzz(context,g,a.teamId,a.questionId,now);g.buzzRevision=(input.buzzRevision||0)+1;return buzzerState(g);
}
function verdict(s,g,ok,now,points){assert(g.status==='answering'&&g.active,'No hay turno activo');const who=g.active;g.verdict={team:who,ok,at:now};if(g.game==='argentinos'){if(g.surveyPhase==='faceoff'){g.faceoffAttempted=arr(g.faceoffAttempted);if(!g.faceoffAttempted.includes(who))g.faceoffAttempted.push(who);g.failed.push(who);g.active=null;g.timer=null;const next=g.queue.find(k=>!g.faceoffAttempted.includes(k));if(next){g.active=next;g.status='answering'}else surveyChoose(g);return s;}assert(g.surveyPhase==='board','El tablero no está iniciado');if(ok){if(points!=null)g.pot+=points;startTimer(g,40,now)}else{g.groupStrikes[who]=(g.groupStrikes[who]||0)+1;if(g.groupStrikes[who]>=3){const order=g.playOrder||[],at=order.indexOf(who),next=order.slice(at+1).find(k=>(g.groupStrikes[k]||0)<3);if(next){g.active=next;g.control=next;startTimer(g,40,now)}else{g.surveyPhase='over';g.status='revealed';g.active=null;g.timer=null;g.potAwarded='none';g.answerShown=true}}else startTimer(g,40,now)}return s;}if(ok){g.scores[who]=(g.scores[who]||0)+(points==null?s.settings.games[g.game].points:points);g.answerShown=true;g.status='revealed';g.active=null;g.timer=null;}else{g.failed.push(who);g.active=null;g.timer=null;if(g.game==='qld'){g.status='revealed';g.answerShown=true;}else{assignNext(s,g,now);if(g.failed.length===g.teamIds.length){g.status='revealed';g.answerShown=true;}}}return s;}
function surveyChoose(g){const entries=Object.entries(g.faceoffRanks||{}).sort((a,b)=>a[1]-b[1]);g.control=entries[0]?.[0]||null;g.active=null;g.timer=null;g.status=g.control?'choice':'faceoffEmpty';g.surveyPhase='choice';}
function awardPot(g,side){g.sideScores=g.sideScores||{};g.sideScores[side]=(g.sideScores[side]||0)+(g.multiplier||1);g.status='revealed';g.surveyPhase='over';g.active=null;g.timer=null;g.answerShown=true;g.potAwarded=side;}

function sessionResult(s,g,now){let points;if(g.game==='argentinos'){const awarded=groupRanking(g.sideScores||{});points=Object.fromEntries(g.teamIds.map(t=>[t,awarded[sideFor(s,g,t)]||0]));}else points=awardScores(g.scores,g.teamIds,GAMES[g.game].mode);result(s,{id:g.id,columnId:g.game,label:GAMES[g.game].name+' · '+g.id.slice(-6),points,scores:copy(g.scores),updatedAt:now});g.status='done';g.timer=null;return s;}
function reduce(input,a,now=Date.now()){const s=normalize(copy(input));if(a.operationId&&s.processed.includes(a.operationId))return s;const g=a.sessionId?s.sessions[a.sessionId]:null;const previous=g?copy(g):null;if(previous?.timer?.running)previous.timer.remaining=Math.max(0,previous.timer.endAt-now);if(a.sessionId)assert(g,'Partida inexistente');switch(a.type){
case 'resetNight':s.teams=[];s.participants=[];s.results={};s.fixture=[];s.sessions={};s.groups={};s.history=[];s.sessionHistory={};s.bracket=null;s.closed=false;s.legacy={};s.presentation={mode:'none',index:0};break;
case 'legacy':s.legacy=copy(a.value);delete s.legacy.impGame;break;
case 'roster':assert(!s.closed,'Ranking cerrado');const referenced=new Set([...s.fixture.flatMap(m=>m.teamIds),...Object.values(s.results).flatMap(r=>Object.keys(r.points)),...Object.values(s.sessions).filter(g=>!['done','closed'].includes(g.status)).flatMap(g=>g.teamIds)]);assert([...referenced].every(id=>a.teams.some(t=>t.id===id)),'Ese equipo tiene encuentros o resultados. Borrá la noche si querés eliminar toda la formación');const activeImp=Object.values(s.sessions).some(g=>g.game==='impostor'&&!['done','closed'].includes(g.status));if(activeImp)assert(s.participants.every(p=>a.participants.some(x=>x.id===p.id&&x.name===p.name&&x.teamId===p.teamId)),'Terminá Impostor antes de cambiar los integrantes actuales');const activeSurvey=Object.values(s.sessions).some(g=>g.game==='argentinos'&&!['done','closed'].includes(g.status));if(activeSurvey)assert(a.teams.length===s.teams.length&&s.teams.every(t=>a.teams.some(x=>x.id===t.id))&&s.participants.every(p=>a.participants.some(x=>x.id===p.id&&x.teamId===p.teamId)),'Terminá 100 antes de cambiar la agrupación');assert(Array.isArray(a.teams)&&Array.isArray(a.participants),'Roster inválido');assert(new Set(a.teams.map(t=>t.id)).size===a.teams.length,'Equipos repetidos');assert(new Set(a.participants.map(p=>p.id)).size===a.participants.length,'Personas repetidas');assert(a.teams.every(t=>t.id&&t.name?.trim()),'Equipos sin nombre');assert(a.participants.every(p=>p.id&&p.name?.trim()&&a.teams.some(t=>t.id===p.teamId)),'Participantes sin equipo');s.teams=copy(a.teams);s.participants=copy(a.participants);if(!activeSurvey)s.groups={};break;
case 'addGame':assert(a.game?.name?.trim(),'Nombre vacío');assert(['sim','duel'].includes(a.game.mode),'Modalidad inválida');s.customGames=s.customGames||{};assert(!GAMES[a.id],'Juego repetido');s.customGames[a.id]={name:a.game.name.trim(),mode:a.game.mode,seconds:0};GAMES[a.id]=s.customGames[a.id];s.settings.games[a.id]={seconds:0,points:1,rounds:1,station:a.id,enabled:true};s.columns.push({id:a.id,name:a.game.name.trim()});break;
case 'appendFixture':{const game=a.game;assert(GAMES[game],'Juego inexistente');assert(s.teams.length>=2,'Creá dos equipos');let r=Math.max(0,...s.fixture.map(m=>m.round))+1;const teams=s.teams.map(t=>t.id),pairs=GAMES[game].mode==='duel'?circlePairs(teams).flat():[teams];for(const pair of pairs)s.fixture.push({id:id(),round:r++,game,teamIds:pair,station:game});break;}
case 'panic':if(a.on){s.panic={on:true,paused:[]};for(const g of Object.values(s.sessions))if(g.timer?.running){g.timer.remaining=Math.max(0,g.timer.endAt-now);g.timer.running=false;s.panic.paused.push(g.id)}}else{for(const id of s.panic?.paused||[]){const t=s.sessions[id]?.timer;if(t&&!t.running){t.endAt=now+t.remaining;t.running=true}}s.panic={on:false,paused:[]}}break;
case 'wallPost':assert(a.text?.trim()||a.photo,'Escribí un mensaje o adjuntá una foto');assert(!a.playerId||s.participants.some(p=>p.id===a.playerId),'Participante inexistente');s.wall.push({id:a.id||id(),playerId:a.playerId||null,text:String(a.text||'').slice(0,1000),photo:a.photo||'',at:now});s.wall=s.wall.slice(-100);break;
case 'wallDelete':s.wall=s.wall.filter(p=>p.id!==a.id);break;
case 'lockBuzzer':g.status='ready';g.timer=null;g.active=null;break;
case 'sessionLabel':g.label=String(a.label||'');break;
case 'reaction':assert(['👏','😂','🔥','❤️','🎉'].includes(a.emoji),'Reacción inválida');s.reaction={emoji:a.emoji,at:now};break;
case 'sessionUndo':{assert(!['done','closed'].includes(g.status),'Reabrí o reiniciá el juego antes de deshacer acciones');const h=arr(s.sessionHistory[g.id]).pop();assert(h,'No hay acción del juego para deshacer');if(h.timer?.running){h.timer.token=id();h.timer.endAt=now+h.timer.remaining;}s.sessions[g.id]=h;break;}
case 'surveyPass':assert(g.game==='argentinos'&&g.active&&!g.steal&&g.strikes===0,'No se puede pasar en este momento');g.active=g.active==='a'?'b':'a';g.control=g.active;startTimer(g,responseSeconds(s,g),now);break;
case 'renameEvent':assert(a.name?.trim(),'Nombre vacío');s.name=a.name.trim();break;
case 'addTeam':assert(!s.closed,'Ranking cerrado');assert(a.name?.trim(),'Nombre vacío');s.teams.push({id:a.id||id(),name:a.name.trim(),order:s.teams.length,photo:''});break;
case 'editTeam':{const t=s.teams.find(x=>x.id===a.id);assert(t,'Equipo inexistente');if(a.name!=null){assert(a.name.trim(),'Nombre vacío');t.name=a.name.trim()}if(a.photo!=null)t.photo=a.photo;break;}
case 'deleteTeam':assert(!s.fixture.some(m=>m.teamIds.includes(a.id))&&!Object.values(s.results).some(r=>a.id in (r.points||{}))&&!s.bracket,'El equipo tiene encuentros o resultados. Resolvé esas referencias antes de eliminarlo');s.teams=s.teams.filter(t=>t.id!==a.id);s.participants.forEach(p=>{if(p.teamId===a.id)p.teamId=null});Object.values(s.groups).forEach(x=>x.teams=x.teams.filter(t=>t!==a.id));break;
case 'reorderTeam':{const i=s.teams.findIndex(t=>t.id===a.id),j=i+a.delta;if(i>=0&&j>=0&&j<s.teams.length)[s.teams[i],s.teams[j]]=[s.teams[j],s.teams[i]];s.teams.forEach((t,i)=>t.order=i);break;}
case 'addParticipant':assert(a.name?.trim(),'Nombre vacío');assert(!a.teamId||s.teams.some(t=>t.id===a.teamId),'Equipo inexistente');s.participants.push({id:a.id||id(),name:a.name.trim(),teamId:a.teamId||null,photo:a.photo||''});break;
case 'editParticipant':{const p=s.participants.find(x=>x.id===a.id);assert(p,'Participante inexistente');assert(!a.teamId||s.teams.some(t=>t.id===a.teamId),'Equipo inexistente');Object.assign(p,{name:a.name?.trim()||p.name,teamId:a.teamId||null,photo:a.photo??p.photo});break;}
case 'deleteParticipant':assert(!Object.values(s.sessions).some(g=>!['done','closed'].includes(g.status)&&g.playerIds.includes(a.id)),'Participante en una ronda de Impostor; reiniciala primero');s.participants=s.participants.filter(p=>p.id!==a.id);break;
case 'column':if(a.remove){assert(!s.closed,'Ranking cerrado');s.columns=s.columns.filter(c=>c.id!==a.id);Object.values(s.results).filter(r=>r.columnId===a.id).forEach(r=>delete s.results[r.id]);}else {const c=s.columns.find(c=>c.id===a.id);if(c)c.name=a.name;else s.columns.push({id:a.id||id(),name:a.name})}break;
case 'result':result(s,a.result);break;
case 'undo':{assert(!s.closed,'Ranking cerrado');const h=s.history.pop();if(h){assert(JSON.stringify(s.results[h.id]||null)===JSON.stringify(h.after),'El resultado cambió; revisalo antes de deshacer');if(h.before)s.results[h.id]=h.before;else delete s.results[h.id]}break;}
case 'clearResults':assert(!s.bracket,'Eliminá explícitamente el cuadro primero');s.results={};s.history=[];s.closed=false;break;
case 'settings':assert(!s.closed,'Ranking cerrado');Object.assign(s.settings,copy(a.values));break;
case 'groups':assert(!Object.values(s.sessions).some(g=>g.game==='argentinos'&&!['done','closed'].includes(g.status)),'Reiniciá o cerrá la partida de 100 Argentinos antes de cambiar agrupaciones');s.groups=copy(a.groups);validateGroups(s);break;
case 'fixture':makeFixture(s,a.repeats);break;
case 'clearFixture':assert(!Object.keys(s.results).length&&!Object.values(s.sessions).some(g=>!['done','closed'].includes(g.status)),'Hay resultados o juegos activos. Resolvelos antes de borrar el fixture');s.fixture=[];break;
case 'editMatch':{const m=s.fixture.find(m=>m.id===a.id);assert(m&&!s.sessions[m.id]&&!s.results[m.id],'No edites un encuentro iniciado');const before=copy(m);Object.assign(m,a.values);if(fixtureAudit(s).errors.length){Object.assign(m,before);throw Error('El cambio genera un conflicto')}break;}
case 'start':startSession(s,a.match,now);break;
case 'resetSession':{s.sessionHistory[a.id]=[];const old=s.sessions[a.id];assert(old,'Partida inexistente');delete s.sessions[a.id];startSession(s,{id:old.id,game:old.game,teamIds:old.teamIds,exhibition:s.closed},now);break;}
case 'closeSession':g.status='closed';g.timer=null;break;
case 'restartQueue':assert(g.game==='movies'&&g.queue.length&&!g.verdict?.ok&&!['done','closed'].includes(g.status),'No hay una cola para repetir');g.failed=[];g.active=g.queue[0];g.status='answering';g.questionId=id();g.verdict=null;startTimer(g,responseSeconds(s,g),now);break;
case 'open':if(g.game==='argentinos'){assert(g.surveyPhase==='faceoff','Elegí una nueva pregunta');g.faceoffRanks={};g.faceoffAttempted=[];}g.buzzSeconds=responseSeconds(s,g);assert(g.game!=='argentinos'||(!g.potAwarded&&!g.steal),'Elegí una nueva pregunta antes de reabrir');assert(!['done','closed'].includes(g.status),'Partida cerrada');g.queue=[];g.failed=[];g.active=null;g.answers={};g.status='open';g.questionId=a.questionId||id();g.answerShown=false;g.verdict=null;g.timer=null;if(g.game==='erudito')startTimer(g,s.settings.games.erudito.seconds,now);break;
case 'buzz':buzz(s,g,a.teamId,a.questionId,now);break;
case 'verdict':verdict(s,g,a.ok,now,a.points);break;
case 'next':assert(!['done','closed'].includes(g.status),'Partida cerrada');g.cardIndex=a.index??g.cardIndex+1;g.card=copy(a.card||{});g.questionId=a.questionId||id();g.status='ready';g.queue=[];g.failed=[];g.active=null;g.answers={};g.timer=null;g.revealed=[];g.surveyPhase=g.game==='argentinos'?'faceoff':null;g.groupStrikes={};g.faceoffRanks={};g.faceoffAttempted=[];g.playOrder=[];g.multiplier=1;g.strikes=0;g.pot=0;g.steal=false;g.control=null;g.originalControl=null;g.potAwarded=null;g.answerShown=false;g.answer='';g.surveyAnswers={};g.frameIndex=0;g.tiles=[];g.lyricLine=1;g.hintsShown=0;g.round++;break;
case 'revealAnswer':g.answerShown=true;if(a.answer!=null)g.answer=a.answer;break;
case 'revealSurvey':assert(g.game==='argentinos'&&g.status==='answering','No hay turno');assert(!g.revealed.includes(a.index),'Respuesta ya revelada');assert(Number.isInteger(a.points)&&a.points>=0&&a.points<=100,'Cantidad inválida');g.revealed.push(a.index);g.surveyAnswers=g.surveyAnswers||{};g.surveyAnswers[a.index]={text:a.text,points:a.points};if(g.surveyPhase==='faceoff'){g.pot+=a.points;g.faceoffRanks[g.active]=a.index;if(a.index===0)surveyChoose(g);else verdict(s,g,true,now);}else{verdict(s,g,true,now,a.points);if(g.revealed.length===a.total)awardPot(g,g.active||g.control)}break;
case 'surveyChoose':assert(g.surveyPhase==='faceoff','Disputa ya cerrada');surveyChoose(g);break;
case 'surveyBoard':assert(g.game==='argentinos'&&g.surveyPhase==='choice'&&g.control,'Resolvé la disputa primero');{const order=[...g.queue,...Object.keys(g.groups).filter(k=>!g.queue.includes(k))],at=order.indexOf(g.control);g.playOrder=order.slice(at).concat(order.slice(0,at));g.surveyPhase='board';g.status='answering';g.active=g.control;g.groupStrikes={};g.failed=[];startTimer(g,40,now);}break;
case 'surveyScores':assert(g.game==='argentinos','Juego incorrecto');Object.entries(a.scores).forEach(([k,v])=>assert(g.groups[k]&&Number.isFinite(v)&&v>=0,'Marcador inválido'));g.sideScores=copy(a.scores);break;
case 'surveyMultiplier':assert([1,2,3].includes(a.value),'Multiplicador inválido');g.multiplier=a.value;break;
case 'surveyShowAll':g.answerShown=true;g.status='revealed';g.surveyPhase='over';g.active=null;g.timer=null;g.potAwarded=g.potAwarded||'none';break;
case 'timer':assert(!['done','closed'].includes(g.status),'Partida cerrada');if(a.command==='start')startTimer(g,a.seconds,now);else if(a.command==='pause'&&g.timer?.running){g.timer.remaining=Math.max(0,g.timer.endAt-now);g.timer.running=false;}else if(a.command==='resume'&&g.timer&&!g.timer.running){g.timer.endAt=now+g.timer.remaining;g.timer.running=true;}else if(a.command==='reset')g.timer=null;break;
case 'expire':if(g.timer?.token!==a.token||!g.timer.running||g.timer.endAt>now)break;g.timer.running=false;g.timer.remaining=0;if(g.status==='answering'&&['movies','qld','argentinos'].includes(g.game))verdict(s,g,false,now);else {g.status=g.game==='erudito'?'answersClosed':'timeup';g.active=null;}break;
case 'scores':if(a.finishBonuses){assert(Object.entries(a.finishBonuses).every(([t,v])=>g.teamIds.includes(t)&&Number.isFinite(v)&&v>=0),'Bonus inválido');g.finishBonuses=copy(a.finishBonuses)}Object.entries(a.scores).forEach(([t,v])=>{assert(g.teamIds.includes(t)&&Number.isFinite(v),'Marcador inválido');g.scores[t]=v;});break;
case 'score':assert(g.teamIds.includes(a.teamId),'Equipo fuera de partida');assert(Number.isFinite(a.value),'Marcador inválido');g.scores[a.teamId]=a.value;break;
case 'submit':assert(!a.questionId||a.questionId===g.questionId,'La pregunta cambió');assert(g.game==='erudito'&&g.status==='open','Respuestas cerradas');assert(g.teamIds.includes(a.teamId),'Equipo fuera de partida');assert(!g.answers[a.teamId],'Tu equipo ya respondió');assert(!g.timer||(g.timer.running&&g.timer.endAt>now),'Tiempo agotado');assert(Number.isFinite(a.value),'Respuesta inválida');g.answers[a.teamId]={value:a.value,at:now};break;
case 'resolveErudito':assert(['open','answersClosed'].includes(g.status),'Pregunta ya resuelta');assert(Number.isFinite(a.value),'Respuesta inválida');{const entries=Object.entries(g.answers);assert(entries.length,'Nadie respondió');const distances=entries.map(([t,v])=>[t,Math.abs(v.value-a.value)]),min=Math.min(...distances.map(x=>x[1]));g.closest=distances.filter(x=>x[1]===min).map(x=>x[0]);if(g.closest.length===1)g.closest.forEach(t=>g.scores[t]=(g.scores[t]||0)+s.settings.games.erudito.points);g.correct=a.value;g.status='revealed';g.timer=null;}break;
case 'sideScores':assert(g.game==='argentinos','Juego incorrecto');assert(Number.isFinite(a.a)&&Number.isFinite(a.b)&&a.a>=0&&a.b>=0,'Marcador inválido');g.sideScores={a:a.a,b:a.b};break;
case 'media':for(const [k,v] of Object.entries(a.values))assert(['frameIndex','tiles','lyricLine','hintsShown'].includes(k),'Control de pista inválido');Object.assign(g,copy(a.values));break;
case 'impRoulette':assert(g.game==='impostor'&&g.playerIds.includes(a.playerId)&&!g.eliminated.includes(a.playerId),'Participante inválido');g.starter=a.playerId;break;
case 'mario':g.mario=copy(a.mario);break;
case 'placements':assert(g.game==='mario','Juego incorrecto');g.placements=copy(a.placements);break;
case 'manualImp':assert(g.game==='impostor','Juego incorrecto');Object.entries(a.points).forEach(([t,p])=>assert(g.teamIds.includes(t)&&Number.isFinite(p),'Puntos inválidos'));g.manualPoints=copy(a.points);break;
case 'impStart':assert(a.playerIds.length>=3,'Impostor requiere al menos tres participantes');assert(!a.double||a.playerIds.length>=6,'Modo doble requiere seis participantes');assert(a.playerIds.every(p=>s.participants.some(x=>x.id===p)),'Participante inexistente');g.playerIds=copy(a.playerIds);g.double=!!a.double;g.eliminated=[];g.caught=[];g.failedVotes=0;g.status='playing';g.impOutcome=null;g.starter=a.starter;g.category=a.category;g.wordId=a.wordId;s.impUsed=arr(s.impUsed);s.impUsed.push(a.wordId);startTimer(g,s.settings.games.impostor.seconds,now);break;
case 'impVote':assert(g.game==='impostor'&&g.status==='playing','Ronda terminada');assert(g.playerIds.includes(a.playerId)&&!g.eliminated.includes(a.playerId),'Participante eliminado');g.eliminated.push(a.playerId);g.lastVote={playerId:a.playerId,impostor:!!a.isImpostor};if(a.isImpostor)g.caught.push(a.playerId);else g.failedVotes++;if(g.caught.length===(g.double?2:1)){g.impOutcome='discovered';g.status='revealed';g.timer=null;}else if(g.failedVotes>=Math.ceil(g.playerIds.length/2)){g.impOutcome='escaped';g.status='revealed';g.timer=null;}else g.starter=a.starter;break;
case 'resetImpWords':s.impUsed=[];break;
case 'impSurrender':assert(g.game==='impostor'&&g.status==='playing','No hay ronda activa');g.impOutcome='escaped';g.status='revealed';g.timer=null;break;
case 'finish':sessionResult(s,g,now);break;
case 'closeRanking':assert(s.teams.length>=2,'Creá al menos dos equipos');assert(s.fixture.every(m=>s.results[m.id]),'Hay encuentros sin resultado');assert(!Object.values(s.sessions).some(g=>g.game!=='palabras'&&!['done','closed'].includes(g.status)),'Hay juegos activos');s.closed=true;break;
case 'reopenRanking':assert(!s.bracket,'Eliminá explícitamente el cuadro antes de reabrir');s.closed=false;break;
case 'bracket':makeBracket(s,a.seeds);break;
case 'bracketResult':recordBracket(s,a.id,a.winner,a.score);break;
case 'bracketGame':assert(s.bracket,'No hay cuadro');s.bracket.rounds[a.round].game=a.game;break;
case 'clearBracket':s.bracket=null;break;
case 'third':assert(s.bracket?.champion,'Terminá la final primero');assert(s.teams.some(t=>t.id===a.teamId)&&a.teamId!==s.bracket.champion,'Tercero inválido');{const final=s.bracket.rounds.at(-1).matches[0];assert(a.teamId!==[final.a,final.b].find(t=>t!==final.winner),'El subcampeón no puede ser tercero');}s.bracket.third=a.teamId;break;
case 'presentation':s.presentation=copy(a.value);break;
case 'photo':s.photos[a.name]=a.url;break;
default:throw Error('Acción desconocida: '+a.type);
}if(previous&&['verdict','revealSurvey','resolveErudito','score','scores','sideScores','next','surveyPass'].includes(a.type)){const list=s.sessionHistory[previous.id]=arr(s.sessionHistory[previous.id]);list.push(previous);s.sessionHistory[previous.id]=list.slice(-20);}for(const session of Object.values(s.sessions))if(['movies','qld','argentinos'].includes(session.game))session.buzzer=buzzerState(session);s.revision=(s.revision||0)+1;s.updatedAt=now;if(a.operationId){s.processed.push(a.operationId);s.processed=s.processed.slice(-300)}return normalize(s);}
const api={GAMES,copy,id,assert,arr,create,normalize,standings,awardScores,autoGroups,groupRanking,fixtureAudit,circlePairs,seedOrder,makeBracket,reduce,reduceBuzzSession,sideFor,validateGroups};if(typeof module!=='undefined')module.exports=api;root.VeladaModel=api;
})(typeof window==='undefined'?globalThis:window);
