const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
function element(){return {innerHTML:'',textContent:'',hidden:false,value:'0',open:false,scrollLeft:0,scrollTop:0,style:{},events:{},addEventListener(event,fn){this.events[event]=fn;},firstElementChild:{style:{}},classList:{add(){},remove(){}},querySelectorAll:()=>[],showModal(){this.open=true;},close(){this.open=false;}};}
const data={},listeners=new Map(),childListeners=new Map();let serial=0,sessionWarm=false,clockOffset=0;
function firebaseShape(x){if(x===null||x===undefined)return null;if(typeof x!=='object')return x;const out=Array.isArray(x)?[]:{};for(const [k,v] of Object.entries(x)){const child=firebaseShape(v);if(child!==null)out[k]=child;}return Object.keys(out).length?out:null;}
const clone=x=>x===undefined?null:JSON.parse(JSON.stringify(x));
function get(p){return p.split('/').filter(Boolean).reduce((o,k)=>o?.[k],data)??null;}
function put(p,v){const parts=p.split('/').filter(Boolean),key=parts.pop();let node=data;for(const k of parts)node=node[k]??={};if(v===null)delete node[key];else node[key]=firebaseShape(clone(v));notify(p);}
function notify(p){for(const [path,cbs] of listeners)if(p===path||p.startsWith(path+'/')||path.startsWith(p+'/'))for(const fn of cbs)fn({val:()=>clone(get(path))});}
function ref(path=''){return {on(event,fn){const map=event==='child_added'?childListeners:listeners;if(!map.has(path))map.set(path,[]);map.get(path).push(fn);if(event==='value')fn({val:()=>clone(get(path))});else for(const [key,val]of Object.entries(get(path)||{}))fn({key,val:()=>clone(val)});},off(event,fn){const map=event==='child_added'?childListeners:listeners;map.set(path,(map.get(path)||[]).filter(x=>x!==fn));},async once(){if(path==='velada/teg/session')sessionWarm=true;return {val:()=>clone(get(path))};},async set(v){put(path,v);},async update(u){for(const [key,val] of Object.entries(u))put(path?path+'/'+key:key,val);},async remove(){put(path,null);},onDisconnect(){return {remove(){}};},async transaction(fn){const next=fn(path==='velada/teg/session'&&!sessionWarm?null:clone(get(path)));if(path==='velada/teg/session')sessionWarm=false;if(next!==undefined)put(path,next);return {committed:next!==undefined,snapshot:{val:()=>clone(get(path))}};},async push(v){const key='cmd'+(++serial);put(path+'/'+key,v);for(const fn of childListeners.get(path)||[])fn({key,val:()=>clone(v)});return ref(path+'/'+key);}};}
put('.info/connected',true);put('.info/serverTimeOffset',0);put('velada/teg/activation',{active:true,id:'fixture-teg-1',round:5,teams:['A / B','C / D','E / F','G / H']});
const db={ref};
function client(uid,mode){const els={},timers=[];const c={console,Date:class extends Date{static now(){return Date.now()+clockOffset;}},Math,JSON,Set,Array,URLSearchParams,crypto:{randomUUID:()=>uid+'-uuid'+(++serial)},location:{search:mode?'?mode='+mode:''},document:{getElementById:i=>els[i]||(els[i]=element()),body:{classList:{add(){},remove(){},toggle(){}}}},sessionStorage:{setItem(){}},setTimeout:()=>1,clearTimeout(){},setInterval:fn=>{timers.push(fn);return 1;},clearInterval(){},confirm:()=>true,TegCloud:{connect:async()=>({db,uid}),login:async p=>{if(p!=='100')throw Error('Clave incorrecta.');return {db,uid};}}};c.window=c;vm.createContext(c);for(const f of ['teg-map.js','teg-engine.js','team-maps.js','teg-config.js','teg-app.js'])vm.runInContext(read(f),c);return {c,els,timers};}
const wait=()=>new Promise(resolve=>setImmediate(resolve));async function flush(){for(let i=0;i<25;i++)await wait();}
function click(data){return {target:{closest:()=>({dataset:data,hasAttribute:k=>k==='data-draft'&&data.draft!==undefined})}};}
(async()=>{
 const host=client('host','host'),tv=client('tv','tv'),p1=client('phone-1'),p2=client('phone-2');await flush();host.els['host-password']=element();host.els['host-password'].value='100';await host.els['host-form'].onsubmit({preventDefault(){}});await flush();assert.equal(get('velada/teg/session').hostId,'host');assert.equal(get('velada/teg/public').status,'lobby');assert(tv.els['map-wrap'].innerHTML.includes('Alaska'));const wrap=host.els['map-wrap'];wrap.clientWidth=800;wrap.clientHeight=220;host.c.TegUI.render();const fitted=parseFloat(wrap.firstElementChild.style.width);assert(fitted<=800);assert(parseFloat(wrap.firstElementChild.style.height)<=220.001);host.els['zoom-in'].onclick();assert(parseFloat(wrap.firstElementChild.style.width)>fitted);host.els['zoom-reset'].onclick();assert.equal(parseFloat(wrap.firstElementChild.style.width),fitted);wrap.events.touchstart({touches:[{clientX:0,clientY:0},{clientX:100,clientY:0}]});wrap.events.touchmove({touches:[{clientX:0,clientY:0},{clientX:200,clientY:0}],preventDefault(){}});assert.equal(parseFloat(wrap.firstElementChild.style.width),fitted*2);wrap.events.touchend();host.els['zoom-reset'].onclick();
 // A delayed first heartbeat must not lock the only host out in the lobby.
 clockOffset+=10000;
 host.els['start-game'].onclick();await flush();const publicGame=get('velada/teg/public');assert.equal(publicGame.status,'running');assert(!publicGame.goals);const team=publicGame.current,name=publicGame.teams[team].name.split('/')[0].trim();
 for(const p of [p1,p2])p.els['team-select'].onclick(click({join:String(team),name}));await flush();assert(get('velada/teg/objectives/phone-1'));assert(get('velada/teg/objectives/phone-2'));assert(p1.els['mission-body'].innerHTML.includes('oculto para los rivales'));assert(!tv.els['mission-body']?.innerHTML);
 const country=publicGame.board.find(p=>p.owner===team).id;for(const p of [p1,p2])p.els['map-wrap'].onclick(click({country:String(country)}));
 assert(p1.els['country-info'].innerHTML.includes('+ Tropa'));p1.els['country-info'].onclick(click({draft:'1'}));p2.els['country-info'].onclick(click({draft:'1'}));await flush();
 assert.equal(get('velada/teg/public').draft[country],1,'Two phones with the same revision cannot place twice');assert.equal(get('velada/teg/session').rev,2);assert.equal(Object.keys(get('velada/teg/commands')||{}).length,0);
 assert(p1.els['map-wrap'].innerHTML.includes('+1'));assert(p2.els['map-wrap'].innerHTML.includes('+1'));assert(tv.els['map-wrap'].innerHTML.includes('+1'));
 host.els['pause-game'].onclick();await flush();assert.equal(get('velada/teg/public').status,'paused');host.els['pause-game'].onclick();await flush();assert.equal(get('velada/teg/public').status,'running');
 // A delayed active heartbeat pauses at the acknowledged lease, keeps the board, and recovers.
 const boardBefore=JSON.stringify(get('velada/teg/session').board),lease=get('velada/teg/session').hostUntil,deadline=get('velada/teg/session').deadline;clockOffset+=10000;for(const tick of host.timers)tick();await flush();assert.equal(get('velada/teg/public').status,'paused');assert.equal(JSON.stringify(get('velada/teg/session').board),boardBefore);assert.equal(get('velada/teg/session').remainingMs,deadline-lease);host.els['pause-game'].onclick();await flush();assert.equal(get('velada/teg/public').status,'running');
 const host2=client('host-other','host');await flush();host2.els['host-password']=element();host2.els['host-password'].value='100';await host2.els['host-form'].onsubmit({preventDefault(){}});await flush();assert(host2.els['host-error'].textContent.includes('Ya hay un conductor'));assert.equal(get('velada/teg/session').hostId,'host');
 // Recover a persisted session after its reinforcement deadline with RTDB-stripped empty continent bonuses.
 const stale=get('velada/teg/session');stale.phase='reinforce';stale.budget={base:3,total:3,continents:{}};stale.draft={};stale.phaseDeadline=Date.now()+clockOffset-2000;stale.hostUntil=Date.now()+clockOffset-1000;put('velada/teg/session',stale);assert(!get('velada/teg/session').budget.continents);await host.els['host-form'].onsubmit({preventDefault(){}});await flush();assert.equal(host.els['host-error'].textContent,'');assert.equal(get('velada/teg/public').status,'paused');
 host.els['finish-game'].onclick();await flush();assert.equal(get('velada/teg/public').status,'finished');assert(get('velada/teg/result').byTeam);assert(tv.els['finish-panel'].innerHTML.includes('pts'));
 // Re-loading TV never resets, creates, claims or starts a session.
 const before=JSON.stringify(get('velada/teg/session'));client('tv-2','tv');await flush();assert.equal(JSON.stringify(get('velada/teg/session')),before);
 console.log('OK: aplicaciones reales de conductor, 2 celulares y TV sobre transporte simulado; sala, inicio, misiones separadas, comando simultáneo rechazado, tablero sincronizado, pausa/reanudación, final y TV sin escrituras.');
})().catch(e=>{console.error(e);process.exitCode=1;});
